#lang racket
; Generated via parse-items.rkt by danm at 2018-11-04T14:39:39 Eastern Standard Time
(require "items.rkt" "recipes.rkt")
(define generated-build-recipes
  '((Ablative-Armour (Cobalt-Mirror . 1) (Sodium-Nitrate . 50))
    (Access-Ramp (Pure-Ferrite . 50) (Carbon . 50))
    (Acid (Mordite . 25) (Fungal-Mould . 600))
    (Advanced-Ion-Battery (Ionised-Cobalt . 25) (Pure-Ferrite . 20))
    (Advanced-Mining-Laser
     (Carbon-Nanotubes . 1)
     (Hermetic-Seal . 1)
     (Technology-Module . 2))
    (Agricultural-Terminal (Chromatic-Metal . 40) (Condensed-Carbon . 25))
    (Albumen-Pearl-Orb (Indium . 60) (Paraffinium . 20))
    (Alternator (Chromatic-Metal . 50) (Magnetised-Ferrite . 6))
    (Amplified-Cartridges (TetraCobalt . 1) (Technology-Module . 1))
    (Analysis-Visor (Carbon-Nanotubes . 1))
    (Ancient-Lock (Ancient-Key . 1))
    (Anomaly-Decal (Carbon . 20))
    (Antimatter (Chromatic-Metal . 25) (Condensed-Carbon . 20))
    (Antimatter-Housing (Oxygen . 30) (Ferrite-Dust . 50))
    (Apollo-Decal (Carbon . 20))
    (Appearance-Modifier (Ferrite-Dust . 10))
    (Aquatic-Crystal (Cyto=Phosphate . 80))
    (Aronium (Paraffinium . 50) (Ionised-Cobalt . 50))
    (Artemis-Decal (Carbon . 20))
    (AtlasPass-v1 (Copper . 200) (Microprocessor . 1))
    (AtlasPass-v2 (Cadmium . 200) (Microprocessor . 1))
    (AtlasPass-v3 (Emeril . 200) (Microprocessor . 1))
    (Atmosphere-Harvester
     (Ammonia . 100)
     (Metal-Plating . 2)
     (Hermetic-Seal . 2))
    (Auto-Sprinkler (Pure-Ferrite . 100) (Oxygen-Capsule . 1))
    (Auto=Propagator (Pure-Ferrite . 100) (Oxygen-Capsule . 1))
    (Autonomous-Mining-Unit
     (Uranium . 100)
     (Metal-Plating . 2)
     (Advanced-Ion-Battery . 1))
    (BRIDGECONNECTOR (Silver . 120) (Tritium . 20))
    (Barnacle (Cyto=Phosphate . 80))
    (Barrel-Fabricator (Ionised-Cobalt . 10) (Antimatter . 1))
    (Barrel-Ioniser (Cobalt-Mirror . 1) (Technology-Module . 1))
    (Base-Computer (Chromatic-Metal . 40))
    (Base-Salvage-Capsule (Pure-Ferrite . 50))
    (Base-Teleport-Module (Ionised-Cobalt . 50) (Ion-Battery . 1))
    (Beacon (Metal-Plating . 1) (Ion-Battery . 2) (Microprocessor . 1))
    (Bed (Condensed-Carbon . 10))
    (Bio=Dome (Magnetised-Ferrite . 25) (Glass . 5))
    (Bio=input-sensor (Chromatic-Metal . 50))
    (Blaze-Javelin
     (Chromatic-Metal . 200)
     (Condensed-Carbon . 150)
     (Technology-Module . 1))
    (Blown-Transistor (Technology-Module . 4))
    (Blueprint-Analyser (Magnetised-Ferrite . 20) (Carbon-Nanotubes . 1))
    (Boiler-Unit (Pure-Ferrite . 100))
    (Boltcaster (Chromatic-Metal . 100) (Carbon-Nanotubes . 3))
    (Boltcaster-SM (Pure-Ferrite . 50))
    (Bronze-Astronaut-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Atlas-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Blob-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Diplo-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Fighter-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Gek-Statue (Pure-Ferrite . 15) (Copper . 15))
    (Bronze-Walker-Statue (Pure-Ferrite . 15) (Copper . 15))
    (CORRIDOR_WINDOW (Ionised-Cobalt . 5) (Glass . 1))
    (Cadmium-Drive (Chromatic-Metal . 250) (Technology-Module . 1))
    (Candelabra-Bloom (Cyto=Phosphate . 80))
    (Canister-Rack (Condensed-Carbon . 10))
    (Captured-Nanode (Chromatic-Metal . 100))
    (Carbon-Crystal (Condensed-Carbon . 150))
    (Carbon-Nanotubes (Carbon . 50))
    (Carnivorous-Bush (Carbon . 40))
    (Ceiling-Light (Pure-Ferrite . 5) (Cobalt . 5))
    (Ceiling-Panel (Pure-Ferrite . 5) (Cobalt . 5))
    (Chair (Pure-Ferrite . 5) (TRA_COMMODITY2 . 1))
    (|Chair-[1]| (Pure-Ferrite . 5) (TRA_COMMODITY2 . 1))
    (|Chair-[2]| (Condensed-Carbon . 5) (TRA_COMMODITY2 . 1))
    (Chloride-Lattice (Chlorine . 150))
    (Circuit-Board (Heat-Capacitor . 1) (Poly-Fibre . 1))
    (Cobalt-Mirror (Ionised-Cobalt . 50))
    (Colossus-Geobay (Metal-Plating . 5) (Ion-Battery . 4) (Paraffinium . 100))
    (Coloured-Light (Sodium . 5))
    (|Coloured-Light-[1]| (Sodium . 5))
    (|Coloured-Light-[2]| (Sodium . 5))
    (|Coloured-Light-[3]| (Sodium . 5))
    (|Coloured-Light-[4]| (Sodium . 5))
    (|Coloured-Light-[5]| (Sodium . 5))
    (Combat-Scope (Ion-Battery . 2) (Technology-Module . 1))
    (Communications-Station (Pure-Ferrite . 20))
    (Concrete-Arch (Ferrite-Dust . 40))
    (Concrete-Door-Frame (Ferrite-Dust . 40))
    (Concrete-Doorway (Ferrite-Dust . 20))
    (Concrete-Floor-Panel (Ferrite-Dust . 20))
    (Concrete-Frontage (Ferrite-Dust . 40) (Pure-Ferrite . 10))
    (Concrete-Half-Arch (Ferrite-Dust . 20))
    (Concrete-Half-Ramp (Ferrite-Dust . 25) (Pure-Ferrite . 5))
    (Concrete-Ramp (Ferrite-Dust . 50) (Pure-Ferrite . 10))
    (Concrete-Roof (Ferrite-Dust . 40))
    (Concrete-Roof-Corner (Ferrite-Dust . 30))
    (Concrete-Roof-Panel (Ferrite-Dust . 25))
    (Concrete-Wall (Ferrite-Dust . 40))
    (Concrete-Window-Panel (Ferrite-Dust . 40) (Glass . 1))
    (Concrete=Framed-Glass-Panel (Ferrite-Dust . 20))
    (Conflict-Scanner (Walker-Brain . 1) (Technology-Module . 1))
    (Construction-Terminal (Chromatic-Metal . 40) (Pure-Ferrite . 25))
    (Containment-Failure
     (Magnetised-Ferrite . 200)
     (Chromatic-Metal . 300)
     (Gold . 180))
    (Cooling-system (Gold . 40) (Oxygen . 10))
    (|Cooling-system-[1]| (Pure-Ferrite . 50))
    (Coprite-Flower (Coprite . 40))
    (Corner-Sofa (Condensed-Carbon . 10))
    (Corrupt-Module (Phosphorus . 100) (Ammonia . 100) (Uranium . 100))
    (Crate-Fabricator (Ionised-Cobalt . 10) (Antimatter . 1))
    (Creature-Hologram (Pure-Ferrite . 100))
    (Cryo=Pump (Hot-Ice . 1) (Thermic-Condensate . 1))
    (Cryogenic-Chamber (Living-Glass . 1) (Cryo=Pump . 1))
    (Cube (Ferrite-Dust . 20))
    (Cuboid-Inner-Door (Pure-Ferrite . 50))
    (Cuboid-Inner-Wall (Pure-Ferrite . 80))
    (Cuboid-Roof-Cap (Pure-Ferrite . 80))
    (Cuboid-Room (Pure-Ferrite . 200))
    (Cuboid-Room-Flooring (Pure-Ferrite . 80))
    (Cuboid-Room-Foundation-Strut (Pure-Ferrite . 80))
    (Cuboid-Room-Foundation-Strut-Quad (Pure-Ferrite . 80))
    (Cuboid-Room-Frame (Pure-Ferrite . 80))
    (Cuboid-Room-Ladder (Pure-Ferrite . 10))
    (Curious-Corn (Carbon . 40))
    (Curly-Coral (Cyto=Phosphate . 80))
    (Curved-Corridor (Pure-Ferrite . 100))
    (Curved-Cuboid-Roof (Pure-Ferrite . 100) (Glass . 1))
    (Curved-Cuboid-Wall (Pure-Ferrite . 100))
    (Curved-Desk (Pure-Ferrite . 5) (Condensed-Carbon . 10))
    (Curved-Freighter-Corridor (Silver . 80) (Tritium . 10))
    (Curved-Pipe (Ferrite-Dust . 20))
    (Curved-Wall (Ferrite-Dust . 20))
    (Cyclotron-Ballista (Dioxite . 200) (Technology-Module . 2))
    (Cylinder (Ferrite-Dust . 20))
    (Cylindrical-Room (Pure-Ferrite . 350))
    (Cylindrical-Room-Frame (Pure-Ferrite . 200))
    (Damaged-Electrode (Ionised-Cobalt . 110))
    (Damaged-Gears (Chromatic-Metal . 600) (Technology-Module . 10))
    (Damaged-Wiring
     (Microprocessor . 10)
     (Hermetic-Seal . 16)
     (Ion-Battery . 12))
    (Dark-Matter (Noospheric-Orb . 1) (Magnetised-Ferrite . 5))
    (|Dawn's-End| (Dark-Matter . 1) (Chromatic-Metal . 25))
    (Decal (Carbon . 20))
    (|Decal-[10]| (Carbon . 20))
    (|Decal-[11]| (Carbon . 20))
    (|Decal-[12]| (Carbon . 20))
    (|Decal-[13]| (Carbon . 20))
    (|Decal-[14]| (Carbon . 20))
    (|Decal-[15]| (Carbon . 20))
    (|Decal-[16]| (Carbon . 20))
    (|Decal-[17]| (Carbon . 20))
    (|Decal-[18]| (Carbon . 20))
    (|Decal-[19]| (Carbon . 20))
    (|Decal-[1]| (Carbon . 20))
    (|Decal-[20]| (Carbon . 20))
    (|Decal-[21]| (Carbon . 20))
    (|Decal-[22]| (Carbon . 20))
    (|Decal-[2]| (Carbon . 20))
    (|Decal-[3]| (Carbon . 20))
    (|Decal-[4]| (Carbon . 20))
    (|Decal-[5]| (Carbon . 20))
    (|Decal-[6]| (Carbon . 20))
    (|Decal-[7]| (Carbon . 20))
    (|Decal-[8]| (Carbon . 20))
    (|Decal-[9]| (Carbon . 20))
    (Deepwater-Chamber (Pure-Ferrite . 350))
    (Deflector-Shield (Chromatic-Metal . 100) (Sodium-Nitrate . 25))
    (Destablised-Sodium (Sodium-Nitrate . 150))
    (Di=hydrogen-Jelly (Di=hydrogen . 40))
    (Dirty-Bronze (Pyrite . 50) (Pure-Ferrite . 100))
    (Door (Pure-Ferrite . 50))
    (Drawers (Pure-Ferrite . 10))
    (Drift-Suspension
     (Magnetised-Ferrite . 50)
     (Paraffinium . 50)
     (Technology-Module . 1))
    (Dwarf-Palm (Carbon . 40))
    (Dyson-Pump (TetraCobalt . 3) (Technology-Module . 2))
    (Echinocactus (Cactus-Flesh . 50) (Pyrite . 25))
    (Economy-Scanner (Microprocessor . 5) (Technology-Module . 1))
    (Efficient-Thrusters
     (Di=hydrogen-Jelly . 1)
     (Tritium . 100)
     (Technology-Module . 2))
    (Efficient-Water-Jets
     (Chromatic-Metal . 100)
     (Oxygen . 100)
     (Living-Pearl . 6))
    (Emeril-Drive (Cadmium . 250) (Technology-Module . 2))
    (Englobed-Shade (Captured-Nanode . 1) (Pure-Ferrite . 100))
    (Enriched-Carbon (Radon . 250) (Condensed-Carbon . 50))
    (Evergreen-Tree (Carbon . 80))
    (Exocraft-Acceleration-Module
     (Magnetised-Ferrite . 15)
     (Chromatic-Metal . 50)
     (Carbon-Nanotubes . 2))
    (Exocraft-Mining-Laser
     (Magnetised-Ferrite . 25)
     (Chromatic-Metal . 100)
     (Oxygen-Capsule . 2))
    (Exocraft-Mining-Laser-Upgrade-Sigma (Pugneum . 50) (Chromatic-Metal . 50))
    (Exocraft-Mounted-Cannon (Pugneum . 50) (Copper . 100))
    (Exocraft-Signal-Booster (Chromatic-Metal . 50) (Microprocessor . 1))
    (Exocraft-Signal-Booster-Upgrade-Sigma
     (Chromatic-Metal . 100)
     (Ion-Battery . 2)
     (Microprocessor . 2))
    (Exocraft-Signal-Booster-Upgrade-Tau
     (Chromatic-Metal . 150)
     (Ion-Battery . 2)
     (Gold . 50))
    (Exocraft-Summoning-Station
     (Magnetised-Ferrite . 100)
     (Ion-Battery . 4)
     (Antimatter . 1))
    (Exocraft-Terminal (Chromatic-Metal . 40) (Di=hydrogen . 25))
    (Expanding-Cube-Gadget (Pure-Ferrite . 30) (Platinum . 30))
    (Explosive-Drones (Walker-Brain . 1) (Gold . 50))
    (Faulty-Hologram (Antimatter . 2))
    (Flag (Pure-Ferrite . 5) (Carbon . 5))
    (|Flag-[1]| (Pure-Ferrite . 5) (Carbon . 5))
    (|Flag-[2]| (Pure-Ferrite . 5) (Carbon . 5))
    (|Flag-[3]| (Pure-Ferrite . 5) (Carbon . 5))
    (Flat-Panel (Ferrite-Dust . 10) (Sodium . 10))
    (Fleet-Command-Room (Silver . 120) (Gold . 40) (Tritium . 10))
    (Floor-Mat (Pure-Ferrite . 5) (Carbon . 5))
    (Flora-Containment (Carbon . 15))
    (|Flora-Containment-[1]| (Carbon . 15))
    (|Flora-Containment-[2]| (Carbon . 15))
    (Foundation (Pure-Ferrite . 150))
    (Foundation-Strut (Pure-Ferrite . 50))
    (Foundation-Strut-Quad (Pure-Ferrite . 50))
    (Fourier-De=Limiter (Salt-Refractor . 1) (Technology-Module . 2))
    (Fragment-Supercharger (Rare-Metal-Element . 3) (Technology-Module . 2))
    (Freighter-Corridor (Silver . 80) (Tritium . 10))
    (Freighter-Cross-Junction (Silver . 80) (Tritium . 10))
    (Freighter-Hyperdrive
     (Chromatic-Metal . 500)
     (Antimatter . 3)
     (Antimatter-Housing . 3))
    (Freighter-Junction (Silver . 80) (Tritium . 10))
    (Freighter-Stairs (Silver . 50))
    (Freighter-Storage-Unit (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[1]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[2]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[3]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[4]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[5]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[6]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[7]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[8]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Freighter-Storage-Unit-[9]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (Freighter-Warp-Reactor-Sigma
     (Cadmium . 250)
     (Oxygen-Filter . 1)
     (Antimatter-Housing . 4))
    (Freighter-Warp-Reactor-Tau
     (Emeril . 250)
     (Sodium-Diode . 1)
     (Antimatter-Housing . 5))
    (Freighter-Warp-Reactor-Theta
     (Indium . 250)
     (Salt-Refractor . 1)
     (Antimatter-Housing . 6))
    (|Frigate-Fuel-(100-Tonnes)| (Di=hydrogen . 100) (Tritium . 100))
    (|Frigate-Fuel-(200-Tonnes)| (Di=hydrogen . 200) (Tritium . 200))
    (|Frigate-Fuel-(50-Tonnes)| (Di=hydrogen . 50) (Tritium . 50))
    (Frostwort (Frost-Crystal . 50) (Dioxite . 25))
    (Fruit-Tree (Carbon . 80))
    (Fuel-Oxidiser (Quad-Servo . 2) (Gold . 50))
    (Fuel-Pump (Ionised-Cobalt . 100) (Pure-Ferrite . 20))
    (Fungal-Cluster (Fungal-Mould . 50) (Ammonia . 25))
    (Fusion-Accelerant (Organic-Catalyst . 1) (Nitrogen-Salt . 1))
    (Fusion-Engine (Magnetised-Ferrite . 25) (Oxygen-Capsule . 2))
    (Fusion-Ignitor
     (Portable-Reactor . 1)
     (Quantum-Processor . 1)
     (Geodesite . 1))
    (Galactic-Hub-Decal (Carbon . 20))
    (Galactic-Trade-Terminal (Magnetised-Ferrite . 25) (Microprocessor . 3))
    (Gamma-Weed (Gamma-Root . 50) (Uranium . 25))
    (Geodesite (Dirty-Bronze . 1) (Herox . 1) (Lemmium . 1))
    (Geology-Cannon (Rare-Metal-Element . 1) (Technology-Module . 1))
    (Glass (Frost-Crystal . 50))
    (Glass-Cuboid-Room (Ionised-Cobalt . 20) (Glass . 2))
    (Glass-Roofed-Corridor (Pure-Ferrite . 100) (Glass . 1))
    (Glass-Tunnel (Glass . 1) (Crystal-Sulphide . 2) (Ferrite-Dust . 25))
    (Gold-Astronaut-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Atlas-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Blob-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Diplo-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Fighter-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Gek-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Gold-Walker-Statue (Pure-Ferrite . 30) (Gold . 30))
    (Grantine (Dioxite . 50) (Ionised-Cobalt . 50))
    (Gravitino-Host
     (Chromatic-Metal . 25)
     (Ionised-Cobalt . 120)
     (Magnetised-Ferrite . 25))
    (Green-Wall-Screen (Pure-Ferrite . 10))
    (Grip-Boost-Suspension
     (Magnetised-Ferrite . 50)
     (Tritium . 50)
     (Technology-Module . 1))
    (HEALTHPLANT (Carbon . 10))
    (Hand-of-Approval-Decal (Carbon . 20))
    (Haz=Mat-Gauntlet (Chromatic-Metal . 50) (Sodium-Nitrate . 20))
    (Hazard-Protection (Ferrite-Dust . 100))
    (Hazard-Protection-Unit
     (Metal-Plating . 1)
     (Ionised-Cobalt . 20)
     (Phosphorus . 50))
    (Health-Station (Metal-Plating . 1) (Ionised-Cobalt . 20) (Uranium . 50))
    (Heart-of-the-Sun (Modified-Quanta . 1) (Gold . 100))
    (Heat-Capacitor (Frost-Crystal . 100) (Solanium . 200))
    (Hermetic-Seal (Condensed-Carbon . 30))
    (Herox (Ammonia . 50) (Ionised-Cobalt . 50))
    (Hi=Slide-Suspension
     (Magnetised-Ferrite . 50)
     (Dioxite . 50)
     (Technology-Module . 1))
    (High=Power-Sonar
     (Salt-Refractor . 1)
     (Crystal-Sulphide . 3)
     (Ferrite-Dust . 50))
    (Holo=Door (Ionised-Cobalt . 40) (Pure-Ferrite . 40))
    (Holographic-Analyser (Oxygen-Filter . 1) (Gold . 50))
    (Holographic-Globe-Gadget (Pure-Ferrite . 30) (Platinum . 30))
    (Hot-Ice (Enriched-Carbon . 1) (Nitrogen-Salt . 1))
    (Hull-Fracture (Chromatic-Metal . 700))
    (Humboldt-Drive (Magnetised-Ferrite . 25) (Oxygen-Capsule . 2))
    (Hydroponic-Tray (Pure-Ferrite . 30) (Ionised-Cobalt . 20) (Carbon . 20))
    (Hydrothermal-Fuel-Cell (Salt . 40) (Cyto=Phosphate . 40) (Carbon . 40))
    (Hyperdrive (Chromatic-Metal . 125) (Microprocessor . 5))
    (Indium-Drive (Emeril . 250) (Technology-Module . 3))
    (Infra=Knife-Accelerator (Phosphorus . 200) (Technology-Module . 2))
    (Infrastructure-Ladder (Ferrite-Dust . 20))
    (Input-terminal (Sodium . 40) (Chromatic-Metal . 50))
    (Interior-Stairs (Pure-Ferrite . 50) (Carbon . 30))
    (Internal-Freighter-Wall (Silver . 50))
    (Ion-Battery (Cobalt . 25) (Ferrite-Dust . 20))
    (Iridesite (Aronium . 1) (Magno=Gold . 1) (Grantine . 1))
    (Jetpack (Ferrite-Dust . 100))
    (L=Shaped-Corridor (Pure-Ferrite . 100))
    (L=Shaped-Glass-Tunnel
     (Glass . 1)
     (Crystal-Sulphide . 2)
     (Ferrite-Dust . 25))
    (Lab-Lamp (Sodium . 10))
    (Ladder (Pure-Ferrite . 30))
    (Landing-Pad (Metal-Plating . 10) (Ion-Battery . 2) (Microprocessor . 2))
    (Large-Freighter-Room (Silver . 120) (Tritium . 20))
    (|Large-Freighter-Room-[1]| (Silver . 120) (Tritium . 20))
    (|Large-Freighter-Room-[2]| (Silver . 120) (Tritium . 20))
    (Large-Glass-Panel (Glass . 1))
    (Large-Hydroponic-Tray
     (Pure-Ferrite . 60)
     (Ionised-Cobalt . 50)
     (Carbon . 50))
    (Large-Monitor-Station (Pure-Ferrite . 5) (Condensed-Carbon . 5))
    (Large-Refiner
     (Chromatic-Metal . 200)
     (Sodium-Nitrate . 100)
     (Microprocessor . 5))
    (Large-Rocket-Tubes (Technology-Module . 2) (Unstable-Plasma . 4))
    (Large-Wall (Ferrite-Dust . 40))
    (Large-Wedge (Ferrite-Dust . 20))
    (Launch-Thruster (Pure-Ferrite . 100) (Di=hydrogen-Jelly . 1))
    (Lemmium (Uranium . 50) (Pure-Ferrite . 100))
    (Life-Support (Ferrite-Dust . 100))
    (Life-Support-Gel (Di=hydrogen-Jelly . 1) (Carbon . 20))
    (Light (Sodium . 5))
    (Light-Balancer (Pure-Ferrite . 100) (Ion-Battery . 1))
    (Light-Table (Sodium . 10) (Ferrite-Dust . 10))
    (|Light-[1]| (Sodium . 5))
    (|Light-[2]| (Sodium . 5))
    (|Light-[3]| (Sodium . 5))
    (Linking-Post (Ferrite-Dust . 10))
    (Liquid-Explosive (Acid . 1) (Unstable-Gel . 1))
    (Living-Glass (Lubricant . 1) (Glass . 5))
    (Load-Balancer (Copper . 50))
    (Locked-Crate (Pure-Ferrite . 10))
    (Locker (Pure-Ferrite . 10))
    (Locking-mechanism (Pure-Ferrite . 30))
    (Loom-Damage (Pyrite . 100) (Dioxite . 100) (Paraffinium . 100))
    (Lubricant (Coprite . 50) (Gamma-Root . 400))
    (Magnetic-Lock (Cobalt . 50))
    (Magno=Gold (Phosphorus . 50) (Ionised-Cobalt . 50))
    (Marine-Shelter (Living-Pearl . 5) (Glass . 1) (Ionised-Cobalt . 20))
    (Mass-Accelerator (Superoxide-Crystal . 1) (Technology-Module . 1))
    (Master-Circuit (Platinum . 10))
    (|Master-Circuit-[1]| (Magnetised-Ferrite . 10))
    (Medium-Refiner (Magnetised-Ferrite . 100) (Di=hydrogen-Jelly . 5))
    (Message-Module (Metal-Plating . 1) (Carbon-Nanotubes . 1))
    (Metal-Arch (Ferrite-Dust . 40))
    (Metal-Door-Frame (Ferrite-Dust . 40))
    (Metal-Doorway (Carbon . 20))
    (Metal-Floor-Panel (Ferrite-Dust . 20))
    (Metal-Frontage (Ferrite-Dust . 40) (Pure-Ferrite . 10))
    (Metal-Half-Arch (Ferrite-Dust . 20))
    (Metal-Half-Ramp (Ferrite-Dust . 25) (Pure-Ferrite . 5))
    (Metal-Plating (Ferrite-Dust . 50))
    (Metal-Ramp (Ferrite-Dust . 50) (Pure-Ferrite . 10))
    (Metal-Roof (Ferrite-Dust . 20) (Ferrite-Dust . 10))
    (Metal-Roof-Corner (Carbon . 20) (Ferrite-Dust . 10))
    (Metal-Roof-Panel (Carbon . 20) (Ferrite-Dust . 10))
    (Metal-Wall (Ferrite-Dust . 40))
    (Metal-Window-Panel (Ferrite-Dust . 40) (Glass . 1))
    (Metal=Framed-Glass-Panel (Ferrite-Dust . 20))
    (Microprocessor (Chromatic-Metal . 40) (Carbon-Nanotubes . 1))
    (Mind-Arc (Chromatic-Metal . 25) (Living-Glass . 1) (Microprocessor . 1))
    (Mind-Control-Device (Sodium-Diode . 1) (Gold . 50))
    (Mineral-Compressor (Cobalt-Mirror . 1) (Gold . 50))
    (Mining-Beam (Ferrite-Dust . 60))
    (Modified-Quanta (Novae-Reclaiment . 1) (Indium . 100))
    (Monitor-Station (Pure-Ferrite . 5) (Cobalt . 5))
    (Moon-Pool-Floor
     (Pure-Ferrite . 350)
     (Crystal-Sulphide . 6)
     (Living-Pearl . 2))
    (Mordite-Root (Mordite . 40))
    (Muster-Point (Pure-Ferrite . 10))
    (NPCEXPLORER001 (Pure-Ferrite . 50))
    (Nada-Decal (Carbon . 20))
    (Nautilon-Cannon
     (Chlorine . 100)
     (Crystal-Sulphide . 6)
     (Living-Pearl . 2))
    (Nautilon-Chamber (Metal-Plating . 5) (Crystal-Sulphide . 4) (Salt . 100))
    (Network-Interface (Magnetised-Ferrite . 10) (Condensed-Carbon . 50))
    (Neural-Stimulator (Chromatic-Metal . 100) (Condensed-Carbon . 100))
    (NipNip (GekNip . 1))
    (Nitrogen-Salt (Nitrogen . 250) (Condensed-Carbon . 50))
    (Nomad-Geobay (Metal-Plating . 5) (Ion-Battery . 4) (Paraffinium . 100))
    (Nonlinear-Optics (Destablised-Sodium . 3) (Technology-Module . 2))
    (|Nonlinear-Optics-[1]| (Cobalt-Mirror . 1) (Technology-Module . 1))
    (Noospheric-Orb (Englobed-Shade . 1) (Ionised-Cobalt . 100))
    (Novae-Reclaiment (State-Phasure . 1) (Emeril . 100))
    (Null-Decal (Carbon . 20))
    (Nutrient-Distributor (Pure-Ferrite . 100) (Ion-Battery . 1))
    (Obsolete-Technology (Technology-Module . 4) (Nanite-Cluster . 100))
    (Octa=Cabinet (Pure-Ferrite . 10))
    (Orange-Wall-Screen (Pure-Ferrite . 10))
    (Organic-Catalyst (Thermic-Condensate . 1) (Enriched-Carbon . 1))
    (Oscilloscope (Pure-Ferrite . 10))
    (Osmotic-Generator
     (Chromatic-Metal . 150)
     (Living-Pearl . 6)
     (Chloride-Lattice . 2))
    (Output-screen (Chromatic-Metal . 50))
    (Oxygen-Capsule (Oxygen . 25) (Ferrite-Dust . 20))
    (Oxygen-Filter (Oxygen . 90) (Pure-Ferrite . 30))
    (Oxygen-Harvester
     (Metal-Plating . 5)
     (Oxygen-Capsule . 5)
     (Di=hydrogen-Jelly . 3))
    (Oxygen-Recycler (Oxygen-Filter . 1))
    (Oxygen-Rerouter
     (Chromatic-Metal . 100)
     (Salt-Refractor . 1)
     (Crystal-Sulphide . 6))
    (Paving (Pure-Ferrite . 25))
    (|Paving-[1]| (Pure-Ferrite . 5))
    (|Paving-[2]| (Pure-Ferrite . 5))
    (Pearl-Offering (Living-Pearl . 1))
    (Personal-Forcefield (Ion-Battery . 2) (Technology-Module . 1))
    (Phase-Beam (Tritium . 100) (Technology-Module . 1))
    (Photic-Jade (|Dawn's-End| . 1) (Copper . 100))
    (Photon-Cannon (Pure-Ferrite . 100) (Sodium-Nitrate . 60))
    (Photonix-Core (Pure-Ferrite . 100) (Condensed-Carbon . 100))
    (Photovoltaic-Panel (Oxygen . 20) (Gold . 40))
    (|Photovoltaic-Panel-[1]|
     (Chromatic-Metal . 50)
     (Magnetised-Ferrite . 6)
     (Cobalt . 50))
    (Pilgrim-Geobay (Metal-Plating . 5) (Ion-Battery . 4) (Paraffinium . 100))
    (Pipe (Ferrite-Dust . 20))
    (Plasma-Launcher (Superoxide-Crystal . 1) (Technology-Module . 1))
    (Plasma-Resonator (Pure-Ferrite . 50))
    (Polo-Decal (Carbon . 20))
    (Poly-Fibre (Cactus-Flesh . 100) (Star-Bulb . 200))
    (Portable-Reactor (Liquid-Explosive . 1) (Fusion-Accelerant . 1))
    (Portable-Refiner (Metal-Plating . 1) (Oxygen . 30))
    (Positron-Ejector (Uranium . 200) (Technology-Module . 2))
    (Potted-Plant (Carbon . 10))
    (Power-Distributor (Gold . 20) (Silver . 40))
    (|Power-Distributor-[1]| (Chromatic-Metal . 50) (Magnetised-Ferrite . 6))
    (Pressure-Chamber (Silver . 100))
    (|Pressure-Chamber-[1]| (Pure-Ferrite . 100) (Oxygen . 40))
    (Projectile-Ammunition (Ferrite-Dust . 6))
    (Pulse-Engine (Hermetic-Seal . 1) (Metal-Plating . 1))
    (Pulse-Spitter (Deuterium . 200) (Technology-Module . 1))
    (Pyramid (Ferrite-Dust . 20))
    (Quantum-Processor (Circuit-Board . 1) (Superconductor . 1))
    (Race-Force-Amplifier (Metal-Plating . 5) (Di=hydrogen-Jelly . 2))
    (Race-Initiator (Metal-Plating . 5) (Microprocessor . 2) (Ion-Battery . 1))
    (Race-Obstacle (Metal-Plating . 5))
    (Radiation-Leak (Paraffinium . 820) (Pugneum . 50))
    (Rare-Metal-Element (Pure-Ferrite . 150))
    (Remembrance (Heart-of-the-Sun . 1) (Platinum . 16))
    (Roamer-Geobay (Metal-Plating . 5) (Ion-Battery . 4) (Paraffinium . 100))
    (Robotic-Arm (Pure-Ferrite . 10))
    (Robotic-Companion (Pugneum . 30) (Platinum . 30))
    (Rocket-Boots (Tritium . 100) (Salt-Refractor . 1))
    (Rocket-Launcher (Copper . 200) (Condensed-Carbon . 100))
    (Roof-Platform (Ferrite-Dust . 20))
    (Rusted-Circuits (Magnetised-Ferrite . 500) (Chlorine . 50))
    (Rusted-Power-Core (Ionised-Cobalt . 100))
    (Safety-Panel (Pure-Ferrite . 100) (Copper . 100))
    (Salt-Refractor (Salt . 100))
    (Save-Point (Metal-Plating . 2) (Di=hydrogen-Jelly . 1))
    (Scanner (Ferrite-Dust . 150))
    (Scatter-Blaster (Pugneum . 200) (Technology-Module . 1))
    (Science-Terminal (Chromatic-Metal . 40) (Magnetised-Ferrite . 25))
    (Security-Alarm (Sodium . 40))
    (Semiconductor (Thermic-Condensate . 1) (Nitrogen-Salt . 1))
    (Server (Pure-Ferrite . 10) (Cobalt . 5))
    (Servo-Arm (Pure-Ferrite . 50))
    (|Servo-Arm-[1]| (Pure-Ferrite . 60))
    (Shattered-Bulwark (Platinum . 400))
    (Shattered-Power-Core (Sodium-Nitrate . 90) (Oxygen . 80))
    (Shelf-Panel (Pure-Ferrite . 10))
    (Shell-Greaser (Chloride-Lattice . 1) (Technology-Module . 1))
    (Shield-Lattice (Sodium-Diode . 1) (Antimatter . 1))
    (Short-Circuit (Chromatic-Metal . 400))
    (Short-Concrete-Wall (Ferrite-Dust . 20))
    (Short-Metal-Wall (Carbon . 20))
    (Short-Wooden-Wall (Carbon . 20))
    (Shutter-Door (Pure-Ferrite . 30))
    (Side-Panel (Ferrite-Dust . 10) (Sodium . 10))
    (Signal-Booster (Metal-Plating . 1) (Carbon-Nanotubes . 1) (Sodium . 15))
    (Silver-Astronaut-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Atlas-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Blob-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Diplo-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Fighter-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Gek-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Silver-Walker-Statue (Pure-Ferrite . 20) (Silver . 20))
    (Simple-Desk (Condensed-Carbon . 10))
    (Sloping-Concrete-Panel (Ferrite-Dust . 20))
    (Sloping-Metal-Panel (Ferrite-Dust . 20))
    (Sloping-Wood-Panel (Carbon . 20))
    (Small-Aquarium (Glass . 2) (Living-Pearl . 1))
    (Small-Concrete-Door (Ferrite-Dust . 20))
    (Small-Concrete-Panel (Ferrite-Dust . 20))
    (Small-Concrete-Wall (Ferrite-Dust . 20))
    (Small-Crate (Pure-Ferrite . 10))
    (Small-Metal-Door (Ferrite-Dust . 20))
    (Small-Metal-Panel (Ferrite-Dust . 20))
    (Small-Metal-Wall (Ferrite-Dust . 20))
    (Small-Wedge (Ferrite-Dust . 20))
    (Small-Wood-Panel (Carbon . 20))
    (Small-Wooden-Door (Carbon . 20))
    (Small-Wooden-Wall (Carbon . 20))
    (Sodium-Diode (Sodium-Nitrate . 40) (Ferrite-Dust . 40))
    (Sofa (Condensed-Carbon . 10))
    (Soil-De=Wormer (Pure-Ferrite . 100) (Ion-Battery . 1))
    (Solar-Vine (Solanium . 50) (Phosphorus . 25))
    (Solenoid (Silver . 50) (Ferrite-Dust . 20))
    (|Solenoid-[1]| (Carbon . 50) (Magnetised-Ferrite . 6))
    (Solid-Cube (Ferrite-Dust . 20))
    (Sphere (Ferrite-Dust . 20))
    (Spindle-Tree (Carbon . 80))
    (Spring-Casing (Pure-Ferrite . 20))
    (Square-Deepwater-Chamber (Pure-Ferrite . 350))
    (Square-Room (Pure-Ferrite . 200))
    (|Square-Room-[1]| (Pure-Ferrite . 350))
    (Standing-Planter (Carbon . 20))
    (Star-Bramble (Star-Bulb . 50) (Paraffinium . 25))
    (Star-Seed (Platinum . 16) (Tritium . 16) (Gold . 16))
    (Starship-Launch-Fuel (Di=hydrogen . 40) (Metal-Plating . 1))
    (Starship-Race-Initiator
     (Metal-Plating . 5)
     (Microprocessor . 2)
     (Ion-Battery . 1))
    (Stasis-Device
     (Quantum-Processor . 1)
     (Cryogenic-Chamber . 1)
     (Iridesite . 1))
    (State-Phasure (Photic-Jade . 1) (Cadmium . 100))
    (Storage-Container (Pure-Ferrite . 5) (Ion-Battery . 1))
    (|Storage-Container-[10]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[1]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[2]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[3]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[4]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[5]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[6]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[7]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[8]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (|Storage-Container-[9]| (Magnetised-Ferrite . 50) (Sodium . 20))
    (Storage-Panel (Pure-Ferrite . 10))
    (Straight-Corridor (Pure-Ferrite . 100))
    (Superconductive-Lock (Sodium-Nitrate . 10))
    (Superconductor (Semiconductor . 1) (Enriched-Carbon . 1))
    (Superoxide-Crystal (Oxygen . 150))
    (Swept-Sofa (Condensed-Carbon . 10))
    (T=Shaped-Corridor (Pure-Ferrite . 100))
    (T=Shaped-Glass-Tunnel
     (Glass . 1)
     (Crystal-Sulphide . 2)
     (Ferrite-Dust . 25))
    (Table (Condensed-Carbon . 10))
    (|Table-[1]| (Condensed-Carbon . 10))
    (|Table-[2]| (Condensed-Carbon . 10))
    (Tall-Cabinet (Condensed-Carbon . 10))
    (Tamper-Prevention-Device (Pugneum . 20))
    (Tech-Panel (Condensed-Carbon . 5) (Cobalt . 5))
    (Teleport-Receiver (Antimatter . 1) (Technology-Module . 3))
    (Terrain-Manipulator (Carbon-Nanotubes . 2) (Di=hydrogen-Jelly . 1))
    (Tethys-Beam
     (Magnetised-Ferrite . 50)
     (Chlorine . 100)
     (Living-Pearl . 10))
    (TetraCobalt (Ionised-Cobalt . 150))
    (Thermic-Condensate (Sulphurine . 250) (Condensed-Carbon . 50))
    (Thermoregulator (Gold . 40))
    (|Thermoregulator-[1]| (Pugneum . 40) (Cobalt . 50))
    (Thin-Concrete-Wall (Ferrite-Dust . 20))
    (Thin-Metal-Wall (Carbon . 20))
    (Thin-Wooden-Wall (Carbon . 20))
    (Tiny-motor (Platinum . 10))
    (|Tiny-motor-[1]| (Sodium . 40) (Condensed-Carbon . 20))
    (Tower-Module (Pure-Ferrite . 50))
    (Transmission-Box (Tritium . 30))
    (|Transmission-Box-[1]| (Mordite . 50) (Coprite . 50))
    (Trident-Key (Trident-Key . 1))
    (Unstable-Gel (Cactus-Flesh . 200))
    (Unstable-Plasma (Oxygen . 50) (Metal-Plating . 1))
    (Upgrade-Module (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[10]| (Oxygen-Capsule . 2) (Technology-Module . 2))
    (|Upgrade-Module-[11]|
     (Sodium . 100)
     (Ion-Battery . 2)
     (Technology-Module . 2))
    (|Upgrade-Module-[12]|
     (Di=hydrogen . 100)
     (Carbon-Nanotubes . 2)
     (Technology-Module . 2))
    (|Upgrade-Module-[13]|
     (Oxygen . 100)
     (Carbon-Nanotubes . 2)
     (Technology-Module . 2))
    (|Upgrade-Module-[14]| (Cobalt . 150) (Technology-Module . 2))
    (|Upgrade-Module-[15]| (Magnetised-Ferrite . 250) (Technology-Module . 2))
    (|Upgrade-Module-[16]|
     (Condensed-Carbon . 150)
     (Gravitino-Ball . 2)
     (Technology-Module . 2))
    (|Upgrade-Module-[17]| (Di=hydrogen-Jelly . 4) (Technology-Module . 2))
    (|Upgrade-Module-[18]| (Unstable-Plasma . 2) (Technology-Module . 2))
    (|Upgrade-Module-[19]| (Pugneum . 100) (Technology-Module . 2))
    (|Upgrade-Module-[1]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[20]| (Condensed-Carbon . 150) (Technology-Module . 2))
    (|Upgrade-Module-[21]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[22]|
     (Silver . 150)
     (Cadmium . 250)
     (Technology-Module . 2))
    (|Upgrade-Module-[23]|
     (Silver . 150)
     (Cadmium . 250)
     (Technology-Module . 2))
    (|Upgrade-Module-[24]|
     (Silver . 150)
     (Cadmium . 250)
     (Technology-Module . 2))
    (|Upgrade-Module-[25]|
     (Silver . 150)
     (Cadmium . 250)
     (Technology-Module . 2))
    (|Upgrade-Module-[26]|
     (Cadmium . 250)
     (Ion-Battery . 2)
     (Technology-Module . 2))
    (|Upgrade-Module-[27]|
     (Chromatic-Metal . 100)
     (Sodium . 100)
     (Technology-Module . 2))
    (|Upgrade-Module-[28]|
     (Chromatic-Metal . 150)
     (Magnetised-Ferrite . 25)
     (Technology-Module . 2))
    (|Upgrade-Module-[29]|
     (Deuterium . 150)
     (Cadmium . 150)
     (Technology-Module . 2))
    (|Upgrade-Module-[2]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[3]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[4]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[5]| (Chromatic-Metal . 80) (Technology-Module . 2))
    (|Upgrade-Module-[6]| (Phosphorus . 100) (Technology-Module . 2))
    (|Upgrade-Module-[7]| (Dioxite . 100) (Technology-Module . 2))
    (|Upgrade-Module-[8]| (Ammonia . 100) (Technology-Module . 2))
    (|Upgrade-Module-[9]| (Uranium . 100) (Technology-Module . 2))
    (Venom-Urchin (Emeril . 100) (Ionised-Cobalt . 100))
    (Vertical-Glass-Tunnel
     (Glass . 1)
     (Crystal-Sulphide . 2)
     (Ferrite-Dust . 25))
    (Viewing-Sphere (Magnetised-Ferrite . 10) (Glass . 3))
    (Wall (Ferrite-Dust . 20))
    (Wall-Fan (Condensed-Carbon . 5) (Cobalt . 5))
    (Wall-Flag (Pure-Ferrite . 5) (Carbon . 5))
    (|Wall-Flag-[1]| (Pure-Ferrite . 5) (Carbon . 5))
    (|Wall-Flag-[2]| (Pure-Ferrite . 5) (Carbon . 5))
    (Wall-Screen (Condensed-Carbon . 5) (Cobalt . 5))
    (Wall-Unit (Pure-Ferrite . 10) (Cobalt . 5))
    (Warp-Cell (Antimatter-Housing . 1) (Antimatter . 1))
    (Warp-Shielding-Sigma
     (Antimatter-Housing . 2)
     (Superoxide-Crystal . 2)
     (Cadmium . 250))
    (Warp-Shielding-Tau
     (Antimatter-Housing . 2)
     (Chloride-Lattice . 2)
     (Emeril . 250))
    (Warp-Shielding-Theta
     (Antimatter-Housing . 2)
     (TetraCobalt . 2)
     (Indium . 250))
    (Watertight-Door (Ferrite-Dust . 25) (Crystal-Sulphide . 1))
    (Waveform-Recycler (Magnetised-Ferrite . 100) (Ion-Battery . 1))
    (Weapon-Rack (Pure-Ferrite . 5) (Cobalt . 5))
    (Weapons-Terminal (Chromatic-Metal . 40) (Pugneum . 25))
    (Window (Ionised-Cobalt . 5) (Glass . 1))
    (|Window-[1]| (Ionised-Cobalt . 5) (Glass . 1))
    (|Window-[2]| (Ionised-Cobalt . 10) (Glass . 1))
    (|Window-[3]| (Ionised-Cobalt . 5) (Glass . 1))
    (Wood-Floor-Panel (Carbon . 20))
    (Wood=Framed-Glass-Panel (Carbon . 20))
    (Wooden-Arch (Carbon . 40))
    (Wooden-Door-Frame (Carbon . 40))
    (Wooden-Doorway (Carbon . 20))
    (Wooden-Frontage (Carbon . 40) (Pure-Ferrite . 10))
    (Wooden-Half-Arch (Carbon . 20))
    (Wooden-Half-Ramp (Carbon . 25) (Pure-Ferrite . 5))
    (Wooden-Ramp (Carbon . 50) (Pure-Ferrite . 10))
    (Wooden-Roof (Carbon . 20) (Ferrite-Dust . 10))
    (Wooden-Roof-Corner (Carbon . 20) (Ferrite-Dust . 10))
    (Wooden-Roof-Panel (Carbon . 20) (Ferrite-Dust . 10))
    (Wooden-Wall (Carbon . 40))
    (Wooden-Window-Panel (Carbon . 40) (Glass . 1))
    (Worktop (Pure-Ferrite . 10))
    (X=Shaped-Corridor (Pure-Ferrite . 100))
    (X=Shaped-Glass-Tunnel
     (Glass . 1)
     (Crystal-Sulphide . 2)
     (Ferrite-Dust . 25))))
(define generated-refiner-recipes
  '((Advanced-Ion-Battery
     1
     (Pure-Ferrite . 10)
     (Sodium-Nitrate . 10)
     (Silver . 10))
    (Ammonia 1 (Nitrogen . 1) (Di=hydrogen . 1))
    (Ammonia 1 (Paraffinium . 2) (Ferrite-Dust . 1))
    (Ammonia 1 (Paraffinium . 2) (Pure-Ferrite . 1))
    (Ammonia 1 (Fungal-Mould . 2) (Salt . 1))
    (Aronium 1 (Paraffinium . 30) (Cobalt . 60) (Tritium . 20))
    (Aronium 1 (Paraffinium . 30) (Ionised-Cobalt . 30) (Tritium . 20))
    (Aronium 1 (Paraffinium . 30) (Cobalt . 60) (Silver . 20))
    (Aronium 1 (Paraffinium . 30) (Ionised-Cobalt . 30) (Silver . 20))
    (Aronium 1 (Paraffinium . 30) (Cobalt . 60) (Gold . 10))
    (Aronium 1 (Paraffinium . 30) (Ionised-Cobalt . 30) (Gold . 10))
    (Aronium 1 (Paraffinium . 30) (Cobalt . 60) (Platinum . 5))
    (Aronium 1 (Paraffinium . 30) (Ionised-Cobalt . 30) (Platinum . 5))
    (Cactus-Flesh 2 (Pyrite . 1) (Cactus-Flesh . 1))
    (Cactus-Flesh 1 (Pyrite . 2) (Oxygen . 1))
    (Cactus-Flesh 1 (Pyrite . 1) (Sulphurine . 1))
    (Cadmium 4 (Cadmium . 1) (Chromatic-Metal . 1))
    (Carbon 1 (Oxygen . 1))
    (Carbon 2 (Condensed-Carbon . 1))
    (Carbon 2 (Fungal-Mould . 1))
    (Carbon 2 (Frost-Crystal . 1))
    (Carbon 2 (Gamma-Root . 1))
    (Carbon 2 (Cactus-Flesh . 1))
    (Carbon 2 (Solanium . 1))
    (Carbon 2 (Star-Bulb . 1))
    (Carbon-Crystal 1 (Carbon . 40) (Condensed-Carbon . 40) (Tritium . 50))
    (Carbon-Crystal 1 (Carbon . 50) (Condensed-Carbon . 50))
    (Chloride-Lattice 1 (Salt . 40) (Chlorine . 40) (Tritium . 50))
    (Chloride-Lattice 1 (Salt . 50) (Chlorine . 50))
    (Chlorine 2 (Cyto=Phosphate . 1) (Salt . 1))
    (Chlorine 5 (Salt . 2) (Oxygen . 2))
    (Chlorine 6 (Chlorine . 1) (Oxygen . 2))
    (Chlorine 2 (Kelp-Sac . 1) (Oxygen . 1))
    (Chlorine 2 (Kelp-Sac . 1) (Pugneum . 1))
    (Chlorine 2 (Kelp-Sac . 1) (Salt . 1))
    (Chlorine 2 (Kelp-Sac . 1) (Chlorine . 1))
    (Chlorine 150 (Chloride-Lattice . 1))
    (Chlorine 1 (Salt . 2))
    (Chromatic-Metal 5 (Silver . 1) (Gold . 1) (Copper . 1))
    (Chromatic-Metal 10 (Silver . 1) (Gold . 1) (Cadmium . 1))
    (Chromatic-Metal 20 (Silver . 1) (Gold . 1) (Emeril . 1))
    (Chromatic-Metal 30 (Silver . 1) (Gold . 1) (Indium . 1))
    (Chromatic-Metal 2 (Cadmium . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 3 (Emeril . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 1 (Copper . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 4 (Indium . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 4 (Activated-Cadmium . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 8 (Activated-Indium . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 6 (Activated-Emeril . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 2 (Activated-Copper . 1) (Pure-Ferrite . 1))
    (Chromatic-Metal 1 (Cadmium . 1))
    (Chromatic-Metal 4 (Indium . 2))
    (Chromatic-Metal 3 (Emeril . 2))
    (Chromatic-Metal 1 (Copper . 2))
    (Chromatic-Metal 2 (Activated-Cadmium . 1))
    (Chromatic-Metal 4 (Activated-Indium . 1))
    (Chromatic-Metal 3 (Activated-Emeril . 1))
    (Chromatic-Metal 1 (Activated-Copper . 1))
    (Cobalt 2 (Ionised-Cobalt . 1))
    (Condensed-Carbon 2 (Uranium . 1) (Di=hydrogen . 1))
    (Condensed-Carbon 5 (Carbon . 2) (Oxygen . 2))
    (Condensed-Carbon 6 (Condensed-Carbon . 1) (Oxygen . 2))
    (Condensed-Carbon 2 (Coprite . 1) (Carbon . 2))
    (Condensed-Carbon 3 (Coprite . 1) (Condensed-Carbon . 1))
    (Condensed-Carbon 2 (Coprite . 1) (Mordite . 1))
    (Condensed-Carbon 1 (Cyto=Phosphate . 1))
    (Condensed-Carbon 150 (Carbon-Crystal . 1))
    (Condensed-Carbon 1 (Carbon . 2))
    (Copper 4 (Copper . 1) (Chromatic-Metal . 1))
    (Coprite 1 (Di=hydrogen . 1) (Carbon . 1))
    (Coprite 3 (Carbon . 2) (Mordite . 1))
    (Coprite 4 (Condensed-Carbon . 1) (Mordite . 1))
    (Coprite 3 (Coprite . 1) (Oxygen . 1))
    (Coprite 1 (Sulphurine . 1) (Nitrogen . 1))
    (Coprite 1 (Mordite . 3))
    (Destablised-Sodium 1 (Sodium . 40) (Sodium-Nitrate . 40) (Tritium . 50))
    (Destablised-Sodium 1 (Sodium . 50) (Sodium-Nitrate . 50))
    (Deuterium 1 (Di=hydrogen . 1) (Tritium . 1))
    (Di=hydrogen 50 (Di=hydrogen-Jelly . 1))
    (Di=hydrogen 1 (Tritium . 5))
    (Di=hydrogen-Jelly 1 (Di=hydrogen . 30))
    (Dioxite 1 (Carbon . 1) (Sodium-Nitrate . 1))
    (Dioxite 2 (Condensed-Carbon . 1) (Sodium-Nitrate . 1))
    (Dioxite 1 (Ammonia . 2) (Ferrite-Dust . 1))
    (Dioxite 1 (Ammonia . 2) (Pure-Ferrite . 1))
    (Dioxite 1 (Frost-Crystal . 2) (Salt . 1))
    (Dirty-Bronze 1 (Pyrite . 30) (Ferrite-Dust . 120) (Tritium . 20))
    (Dirty-Bronze 1 (Pyrite . 30) (Pure-Ferrite . 60) (Tritium . 20))
    (Dirty-Bronze 1 (Pyrite . 30) (Ferrite-Dust . 120) (Silver . 20))
    (Dirty-Bronze 1 (Pyrite . 30) (Pure-Ferrite . 60) (Silver . 20))
    (Dirty-Bronze 1 (Pyrite . 30) (Ferrite-Dust . 120) (Gold . 10))
    (Dirty-Bronze 1 (Pyrite . 30) (Pure-Ferrite . 60) (Gold . 10))
    (Dirty-Bronze 1 (Pyrite . 30) (Ferrite-Dust . 120) (Platinum . 5))
    (Dirty-Bronze 1 (Pyrite . 30) (Pure-Ferrite . 60) (Platinum . 5))
    (Emeril 4 (Emeril . 1) (Chromatic-Metal . 1))
    (Enriched-Carbon 1 (Radon . 100) (Carbon . 20) (Salt . 10))
    (Enriched-Carbon 1 (Radon . 100) (Condensed-Carbon . 10) (Salt . 10))
    (Enriched-Carbon 1 (Radon . 100) (Carbon . 20) (Chlorine . 5))
    (Enriched-Carbon 1 (Radon . 100) (Condensed-Carbon . 10) (Chlorine . 5))
    (Ferrite-Dust 1 (Paraffinium . 1))
    (Ferrite-Dust 1 (Pyrite . 1))
    (Ferrite-Dust 1 (Ammonia . 1))
    (Ferrite-Dust 1 (Uranium . 1))
    (Ferrite-Dust 1 (Dioxite . 1))
    (Ferrite-Dust 1 (Phosphorus . 1))
    (Ferrite-Dust 2 (Rusted-Metal . 1))
    (Frost-Crystal 2 (Dioxite . 1) (Frost-Crystal . 1))
    (Frost-Crystal 1 (Dioxite . 2) (Oxygen . 1))
    (Frost-Crystal 1 (Dioxite . 1) (Radon . 1))
    (Fungal-Mould 2 (Ammonia . 1) (Fungal-Mould . 1))
    (Fungal-Mould 1 (Ammonia . 2) (Oxygen . 1))
    (Fungal-Mould 1 (Ammonia . 1) (Nitrogen . 1))
    (Gamma-Root 2 (Uranium . 1) (Gamma-Root . 1))
    (Gamma-Root 1 (Uranium . 2) (Oxygen . 1))
    (Gamma-Root 1 (Uranium . 1) (Radon . 1))
    (Glass 1 (Cyto=Phosphate . 50) (Salt . 50))
    (Glass 1 (Silver . 100))
    (Gold 10 (Ferrite-Dust . 1) (Oxygen . 1) (Emeril . 1))
    (Gold 1 (Coprite . 1) (Residual-Goop . 1))
    (Gold 1 (Mordite . 1) (Pugneum . 1))
    (Gold 2 (Coprite . 1) (Pugneum . 1))
    (Gold 100 (Living-Pearl . 1))
    (Gold 125 (Lemmium . 1))
    (Gold 125 (Magno=Gold . 1))
    (Gold 125 (Grantine . 1))
    (Grantine 1 (Dioxite . 30) (Cobalt . 60) (Tritium . 20))
    (Grantine 1 (Dioxite . 30) (Ionised-Cobalt . 30) (Tritium . 20))
    (Grantine 1 (Dioxite . 30) (Cobalt . 60) (Silver . 20))
    (Grantine 1 (Dioxite . 30) (Ionised-Cobalt . 30) (Silver . 20))
    (Grantine 1 (Dioxite . 30) (Cobalt . 60) (Gold . 10))
    (Grantine 1 (Dioxite . 30) (Ionised-Cobalt . 30) (Gold . 10))
    (Grantine 1 (Dioxite . 30) (Cobalt . 60) (Platinum . 5))
    (Grantine 1 (Dioxite . 30) (Ionised-Cobalt . 30) (Platinum . 5))
    (Herox 1 (Ammonia . 30) (Cobalt . 60) (Tritium . 20))
    (Herox 1 (Ammonia . 30) (Ionised-Cobalt . 30) (Tritium . 20))
    (Herox 1 (Ammonia . 30) (Cobalt . 60) (Silver . 20))
    (Herox 1 (Ammonia . 30) (Ionised-Cobalt . 30) (Silver . 20))
    (Herox 1 (Ammonia . 30) (Cobalt . 60) (Gold . 10))
    (Herox 1 (Ammonia . 30) (Ionised-Cobalt . 30) (Gold . 10))
    (Herox 1 (Ammonia . 30) (Cobalt . 60) (Platinum . 5))
    (Herox 1 (Ammonia . 30) (Ionised-Cobalt . 30) (Platinum . 5))
    (Indium 4 (Indium . 1) (Chromatic-Metal . 1))
    (Ion-Battery 1 (Ferrite-Dust . 10) (Silver . 10) (Sodium . 10))
    (Ionised-Cobalt 5 (Cobalt . 2) (Oxygen . 2))
    (Ionised-Cobalt 6 (Ionised-Cobalt . 1) (Oxygen . 2))
    (Ionised-Cobalt 2 (Marrow-Bulb . 1) (Oxygen . 1))
    (Ionised-Cobalt 2 (Marrow-Bulb . 1) (Pugneum . 1))
    (Ionised-Cobalt 2 (Marrow-Bulb . 1) (Cobalt . 1))
    (Ionised-Cobalt 2 (Marrow-Bulb . 1) (Ionised-Cobalt . 1))
    (Ionised-Cobalt 150 (TetraCobalt . 1))
    (Ionised-Cobalt 1 (Cobalt . 2))
    (Kelp-Sac 1 (Salt . 1) (Nitrogen . 1))
    (Lemmium 1 (Uranium . 30) (Ferrite-Dust . 120) (Tritium . 20))
    (Lemmium 1 (Uranium . 30) (Pure-Ferrite . 60) (Tritium . 20))
    (Lemmium 1 (Uranium . 30) (Ferrite-Dust . 120) (Silver . 20))
    (Lemmium 1 (Uranium . 30) (Pure-Ferrite . 60) (Silver . 20))
    (Lemmium 1 (Uranium . 30) (Ferrite-Dust . 120) (Gold . 10))
    (Lemmium 1 (Uranium . 30) (Pure-Ferrite . 60) (Gold . 10))
    (Lemmium 1 (Uranium . 30) (Ferrite-Dust . 120) (Platinum . 5))
    (Lemmium 1 (Uranium . 30) (Pure-Ferrite . 60) (Platinum . 5))
    (Life-Support-Gel
     1
     (Oxygen . 10)
     (Condensed-Carbon . 10)
     (Di=hydrogen . 10))
    (Living-Slime 50 (Hypnotic-Eye . 1))
    (Living-Slime 1 (Viscous-Fluids . 1))
    (Magnetised-Ferrite 5 (Ferrite-Dust . 1) (Pure-Ferrite . 1) (Silver . 1))
    (Magnetised-Ferrite 8 (Ferrite-Dust . 1) (Pure-Ferrite . 1) (Gold . 1))
    (Magnetised-Ferrite
     12
     (Ferrite-Dust . 1)
     (Pure-Ferrite . 1)
     (Platinum . 1))
    (Magnetised-Ferrite 1 (Ferrite-Dust . 1) (Carbon . 1))
    (Magnetised-Ferrite 2 (Ferrite-Dust . 1) (Condensed-Carbon . 1))
    (Magnetised-Ferrite 2 (Pure-Ferrite . 1) (Carbon . 1))
    (Magnetised-Ferrite 3 (Pure-Ferrite . 1) (Condensed-Carbon . 1))
    (Magnetised-Ferrite 3 (Pure-Ferrite . 2) (Pugneum . 1))
    (Magnetised-Ferrite 4 (Magnetised-Ferrite . 3) (Pugneum . 1))
    (Magnetised-Ferrite 10 (Platinum . 1) (Oxygen . 1))
    (Magnetised-Ferrite 4 (Indium . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 2 (Cadmium . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 3 (Emeril . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 1 (Copper . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 4 (Activated-Cadmium . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 8 (Activated-Indium . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 6 (Activated-Emeril . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 2 (Activated-Copper . 1) (Ferrite-Dust . 1))
    (Magnetised-Ferrite 1 (Pure-Ferrite . 2))
    (Magno=Gold 1 (Phosphorus . 30) (Cobalt . 60) (Tritium . 20))
    (Magno=Gold 1 (Phosphorus . 30) (Ionised-Cobalt . 30) (Tritium . 20))
    (Magno=Gold 1 (Phosphorus . 30) (Cobalt . 60) (Silver . 20))
    (Magno=Gold 1 (Phosphorus . 30) (Ionised-Cobalt . 30) (Silver . 20))
    (Magno=Gold 1 (Phosphorus . 30) (Cobalt . 60) (Gold . 10))
    (Magno=Gold 1 (Phosphorus . 30) (Ionised-Cobalt . 30) (Gold . 10))
    (Magno=Gold 1 (Phosphorus . 30) (Cobalt . 60) (Platinum . 5))
    (Magno=Gold 1 (Phosphorus . 30) (Ionised-Cobalt . 30) (Platinum . 5))
    (Marrow-Bulb 3 (Sodium . 2) (Mordite . 1))
    (Marrow-Bulb 4 (Sodium-Nitrate . 1) (Mordite . 1))
    (Marrow-Bulb 1 (Cobalt . 1) (Nitrogen . 1))
    (Mordite 1 (Di=hydrogen . 1) (Condensed-Carbon . 1))
    (Mordite 1 (Carbon . 1) (Pugneum . 1))
    (Mordite 2 (Condensed-Carbon . 1) (Pugneum . 1))
    (Mordite 2 (Coprite . 3))
    (Nanite-Cluster 1 (Silver . 250) (Gold . 250) (Platinum . 250))
    (Nanite-Cluster 1 (Coprite . 1) (Hexite . 1))
    (Nanite-Cluster 50 (Hadal-Core . 1))
    (Nanite-Cluster 50 (Larval-Core . 1))
    (Nanite-Cluster 1 (Platinum . 5))
    (Nanite-Cluster 1 (Pugneum . 10))
    (Nanite-Cluster 1 (Runaway-Mould . 5))
    (Nitrogen 1 (Radon . 1) (Oxygen . 1))
    (Nitrogen 1 (Radon . 1) (Chromatic-Metal . 1))
    (Nitrogen 1 (Radon . 3))
    (Nitrogen-Salt 1 (Nitrogen . 100) (Carbon . 20) (Salt . 10))
    (Nitrogen-Salt 1 (Nitrogen . 100) (Condensed-Carbon . 10) (Salt . 10))
    (Nitrogen-Salt 1 (Nitrogen . 100) (Carbon . 20) (Chlorine . 5))
    (Nitrogen-Salt 1 (Nitrogen . 100) (Condensed-Carbon . 10) (Chlorine . 5))
    (Oxygen 10 (Fungal-Mould . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 10 (Frost-Crystal . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 10 (Cactus-Flesh . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 10 (Solanium . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 10 (Gamma-Root . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 10 (Star-Bulb . 1) (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 2 (Kelp-Sac . 1) (Carbon . 1))
    (Oxygen 2 (Kelp-Sac . 1) (Condensed-Carbon . 1))
    (Oxygen 150 (Superoxide-Crystal . 1))
    (Oxygen 1 (Kelp-Sac . 1))
    (Paraffinium 2 (Silver . 1) (Oxygen . 1))
    (Paraffinium 1 (Pyrite . 2) (Ferrite-Dust . 1))
    (Paraffinium 1 (Pyrite . 2) (Pure-Ferrite . 1))
    (Paraffinium 1 (Star-Bulb . 2) (Salt . 1))
    (Paraffinium 1 (Sulphurine . 1) (Ferrite-Dust . 1))
    (Paraffinium 2 (Sulphurine . 1) (Pure-Ferrite . 1))
    (Paraffinium 3 (Sulphurine . 1) (Magnetised-Ferrite . 1))
    (Phosphorus 1 (Dioxite . 2) (Ferrite-Dust . 1))
    (Phosphorus 1 (Dioxite . 2) (Pure-Ferrite . 1))
    (Phosphorus 1 (Solanium . 2) (Salt . 1))
    (Platinum 10 (Ferrite-Dust . 1) (Oxygen . 1) (Chromatic-Metal . 250))
    (Platinum 1 (Gold . 1) (Silver . 1))
    (Platinum 250 (Geodesite . 1))
    (Platinum 250 (Iridesite . 1))
    (Pure-Ferrite 3 (Ferrite-Dust . 2) (Pugneum . 1))
    (Pure-Ferrite 150 (Rare-Metal-Element . 1))
    (Pure-Ferrite 1 (Ferrite-Dust . 1))
    (Pure-Ferrite 2 (Magnetised-Ferrite . 1))
    (Pyrite 2 (Gold . 1) (Oxygen . 1))
    (Pyrite 1 (Uranium . 2) (Ferrite-Dust . 1))
    (Pyrite 1 (Uranium . 2) (Pure-Ferrite . 1))
    (Pyrite 1 (Cactus-Flesh . 2) (Salt . 1))
    (Pyrite 1 (Gold . 1))
    (Radon 1 (Sulphurine . 1) (Oxygen . 1))
    (Radon 1 (Sulphurine . 1) (Chromatic-Metal . 1))
    (Radon 1 (Sulphurine . 3))
    (Rare-Metal-Element
     1
     (Ferrite-Dust . 35)
     (Pure-Ferrite . 35)
     (Magnetised-Ferrite . 35))
    (Rare-Metal-Element
     1
     (Oxygen . 20)
     (Magnetised-Ferrite . 20)
     (Tritium . 25))
    (Rare-Metal-Element 1 (Magnetised-Ferrite . 25) (Oxygen . 50))
    (Runaway-Mould 1 (Living-Slime . 1))
    (Rusted-Metal 2 (Pure-Ferrite . 1) (Oxygen . 1))
    (Rusted-Metal 1 (Ferrite-Dust . 1) (Oxygen . 1))
    (Salt 1 (Di=hydrogen . 1) (Oxygen . 1))
    (Salt 2 (Chlorine . 1))
    (Silver 250 (Aronium . 1))
    (Silver 250 (Dirty-Bronze . 1))
    (Silver 250 (Herox . 1))
    (Sodium 2 (Marrow-Bulb . 1) (Carbon . 1))
    (Sodium 2 (Marrow-Bulb . 1) (Condensed-Carbon . 1))
    (Sodium 2 (Sodium-Nitrate . 1))
    (Sodium 1 (Marrow-Bulb . 1))
    (Sodium-Nitrate 1 (Sodium . 1) (Oxygen . 1))
    (Sodium-Nitrate 2 (Sodium-Nitrate . 1) (Oxygen . 1))
    (Sodium-Nitrate 1 (Carbon . 1) (Sodium . 1))
    (Sodium-Nitrate 2 (Condensed-Carbon . 1) (Sodium . 1))
    (Sodium-Nitrate 1 (Sodium . 1) (Pugneum . 1))
    (Sodium-Nitrate 3 (Sodium-Nitrate . 1) (Pugneum . 1))
    (Sodium-Nitrate 1 (Nitrogen . 1) (Sodium . 1))
    (Sodium-Nitrate 2 (Nitrogen . 1) (Sodium-Nitrate . 1))
    (Sodium-Nitrate 2 (Marrow-Bulb . 1) (Sodium . 1))
    (Sodium-Nitrate 2 (Kelp-Sac . 1) (Sodium . 1))
    (Sodium-Nitrate 2 (Coprite . 1) (Sodium . 1))
    (Sodium-Nitrate 2 (Marrow-Bulb . 1) (Sodium-Nitrate . 1))
    (Sodium-Nitrate 2 (Kelp-Sac . 1) (Sodium-Nitrate . 1))
    (Sodium-Nitrate 2 (Coprite . 1) (Sodium-Nitrate . 1))
    (Sodium-Nitrate 1 (Nitrogen . 1) (Ferrite-Dust . 1))
    (Sodium-Nitrate 2 (Nitrogen . 1) (Pure-Ferrite . 1))
    (Sodium-Nitrate 3 (Nitrogen . 1) (Magnetised-Ferrite . 1))
    (Sodium-Nitrate 50 (Crystal-Sulphide . 1))
    (Sodium-Nitrate 150 (Destablised-Sodium . 1))
    (Sodium-Nitrate 1 (Sodium . 2))
    (Solanium 1 (Sulphurine . 1) (Di=hydrogen . 1))
    (Solanium 2 (Phosphorus . 1) (Solanium . 1))
    (Solanium 1 (Phosphorus . 2) (Oxygen . 1))
    (Solanium 1 (Phosphorus . 1) (Sulphurine . 1))
    (Star-Bulb 2 (Paraffinium . 1) (Star-Bulb . 1))
    (Star-Bulb 1 (Paraffinium . 2) (Oxygen . 1))
    (Star-Bulb 1 (Paraffinium . 1) (Nitrogen . 1))
    (Starship-Launch-Fuel
     1
     (Di=hydrogen . 10)
     (Ferrite-Dust . 20)
     (Sodium-Nitrate . 5))
    (Starship-Launch-Fuel
     1
     (Di=hydrogen . 10)
     (Pure-Ferrite . 20)
     (Sodium . 10))
    (Starship-Launch-Fuel
     1
     (Di=hydrogen . 10)
     (Magnetised-Ferrite . 10)
     (Sodium-Nitrate . 5))
    (Sulphurine 1 (Nitrogen . 1) (Oxygen . 1))
    (Sulphurine 1 (Nitrogen . 1) (Chromatic-Metal . 1))
    (Sulphurine 1 (Nitrogen . 3))
    (Superoxide-Crystal 1 (Oxygen . 40) (Uranium . 40) (Tritium . 50))
    (Superoxide-Crystal 1 (Oxygen . 100) (Tritium . 50))
    (TetraCobalt 1 (Cobalt . 40) (Ionised-Cobalt . 40) (Tritium . 50))
    (TetraCobalt 1 (Cobalt . 50) (Ionised-Cobalt . 50))
    (Thermic-Condensate 1 (Sulphurine . 100) (Carbon . 20) (Salt . 10))
    (Thermic-Condensate
     1
     (Sulphurine . 100)
     (Condensed-Carbon . 10)
     (Salt . 10))
    (Thermic-Condensate 1 (Sulphurine . 100) (Carbon . 20) (Chlorine . 5))
    (Thermic-Condensate
     1
     (Sulphurine . 100)
     (Condensed-Carbon . 10)
     (Chlorine . 5))
    (Unstable-Plasma 1 (Oxygen . 10) (Ferrite-Dust . 20) (Carbon . 20))
    (Unstable-Plasma
     1
     (Oxygen . 10)
     (Ferrite-Dust . 20)
     (Condensed-Carbon . 10))
    (Unstable-Plasma 1 (Oxygen . 10) (Pure-Ferrite . 20) (Carbon . 20))
    (Unstable-Plasma
     1
     (Oxygen . 10)
     (Condensed-Carbon . 10)
     (Pure-Ferrite . 20))
    (Uranium 1 (Radon . 1) (Di=hydrogen . 1))
    (Uranium 1 (Phosphorus . 2) (Ferrite-Dust . 1))
    (Uranium 1 (Phosphorus . 2) (Pure-Ferrite . 1))
    (Uranium 1 (Gamma-Root . 2) (Salt . 1))
    (Uranium 1 (Ferrite-Dust . 1) (Radon . 1))
    (Uranium 2 (Radon . 1) (Pure-Ferrite . 1))
    (Uranium 3 (Radon . 1) (Magnetised-Ferrite . 1))
    (Viscous-Fluids 1 (Residual-Goop . 1))
    (Warp-Cell 1 (Condensed-Carbon . 25) (Sodium . 10) (Chromatic-Metal . 250))
    (Warp-Cell 1 (Carbon . 50) (Sodium-Nitrate . 5) (Chromatic-Metal . 250))
    (Warp-Cell
     1
     (Condensed-Carbon . 25)
     (Sodium-Nitrate . 5)
     (Chromatic-Metal . 250))))
(for
 ((r generated-build-recipes))
 (add-recipe-by-names 'build (car r) 1 (cdr r)))
(for
 ((r generated-refiner-recipes))
 (add-recipe-by-names 'refine (first r) (second r) (list-tail r 2)))
