#lang racket
; Generated via parse-items.rkt by danm at 2018-10-30T22:52:38 Eastern Daylight Time
(require "items.rkt" "recipes.rkt")
(define generated-recipes
  '(("T_EXENG" ("TECH_COMP" . "2") ("STELLAR2" . "80"))
    ("T_BOOST" ("TECH_COMP" . "2") ("STELLAR2" . "80"))
    ("T_EXLAS" ("TECH_COMP" . "2") ("STELLAR2" . "80"))
    ("T_EXGUN" ("TECH_COMP" . "2") ("STELLAR2" . "80"))
    ("T_HOTPROT" ("TECH_COMP" . "2") ("HOT1" . "100"))
    ("T_COLDPROT" ("TECH_COMP" . "2") ("COLD1" . "100"))
    ("T_TOX" ("TECH_COMP" . "2") ("TOXIC1" . "100"))
    ("T_RAD" ("TECH_COMP" . "2") ("RADIO1" . "100"))
    ("T_UNW" ("TECH_COMP" . "2") ("PRODFUEL1" . "2"))
    ("T_SHIELD" ("TECH_COMP" . "2") ("POWERCELL" . "2") ("CATALYST1" . "100"))
    ("T_JET" ("TECH_COMP" . "2") ("NANOTUBES" . "2") ("LAUNCHSUB" . "100"))
    ("T_ENERGY" ("TECH_COMP" . "2") ("NANOTUBES" . "2") ("OXYGEN" . "100"))
    ("T_SMG" ("TECH_COMP" . "2") ("CAVE1" . "150"))
    ("T_SHOTGUN" ("TECH_COMP" . "2") ("LAND3" . "250"))
    ("T_RAIL" ("TECH_COMP" . "2") ("GRAVBALL" . "2") ("FUEL2" . "150"))
    ("T_T_GREN" ("TECH_COMP" . "2") ("JELLY" . "4"))
    ("T_GRENADE" ("TECH_COMP" . "2") ("GRENFUEL1" . "2"))
    ("T_BOLT" ("TECH_COMP" . "2") ("ROBOT1" . "100"))
    ("T_LASER" ("TECH_COMP" . "2") ("FUEL2" . "150"))
    ("T_SCAN" ("TECH_COMP" . "2") ("STELLAR2" . "80"))
    ("T_SHIPBLOB" ("TECH_COMP" . "2") ("RED2" . "250") ("ASTEROID1" . "150"))
    ("T_SHIPMINI" ("TECH_COMP" . "2") ("RED2" . "250") ("ASTEROID1" . "150"))
    ("T_SHIPSHOT" ("TECH_COMP" . "2") ("RED2" . "250") ("ASTEROID1" . "150"))
    ("T_SHIPLAS" ("TECH_COMP" . "2") ("RED2" . "250") ("ASTEROID1" . "150"))
    ("T_SHIPGUN" ("TECH_COMP" . "2") ("POWERCELL" . "2") ("RED2" . "250"))
    ("T_SHIPSHLD"
     ("TECH_COMP" . "2")
     ("CATALYST1" . "100")
     ("STELLAR2" . "100"))
    ("T_HDRIVE" ("TECH_COMP" . "2") ("LAND3" . "25") ("STELLAR2" . "150"))
    ("T_SHIPJUMP" ("TECH_COMP" . "2") ("RED2" . "150") ("LAUNCHSUB2" . "150"))
    ("EXOPOD_TECH3" ("OXYGEN" . "80") ("CATALYST2" . "90"))
    ("EXOPOD_TECH2" ("CAVE2" . "110"))
    ("EXOPOD_TECH1" ("ANTIMATTER" . "2"))
    ("MAINT_FRIG10" ("ROCKETSUB" . "30"))
    ("MAINT_FRIG9" ("ASTEROID2" . "40") ("OXYGEN" . "20"))
    ("MAINT_FRIG8" ("ASTEROID1" . "40") ("ASTEROID2" . "20"))
    ("MAINT_FRIG7" ("ASTEROID3" . "10"))
    ("MAINT_FRIG6" ("ASTEROID1" . "100"))
    ("MAINT_FRIG5" ("LAND1" . "20") ("ASTEROID1" . "50"))
    ("MAINT_FRIG4" ("LAND2" . "50"))
    ("MAINT_FRIG3" ("ASTEROID2" . "40"))
    ("MAINT_FRIG2" ("OXYGEN" . "10") ("ASTEROID2" . "40"))
    ("MAINT_FRIG1" ("ASTEROID3" . "10"))
    ("MAINT_ARTIFACT" ("ARTIFACT_KEY" . "1"))
    ("MAINT_REFINER")
    ("MAINT_PORTAL16")
    ("MAINT_PORTAL15")
    ("MAINT_PORTAL14")
    ("MAINT_PORTAL13")
    ("MAINT_PORTAL12")
    ("MAINT_PORTAL11")
    ("MAINT_PORTAL10")
    ("MAINT_PORTAL9")
    ("MAINT_PORTAL8")
    ("MAINT_PORTAL7")
    ("MAINT_PORTAL6")
    ("MAINT_PORTAL5")
    ("MAINT_PORTAL4")
    ("MAINT_PORTAL3")
    ("MAINT_PORTAL2")
    ("MAINT_PORTAL1")
    ("MAINT_TECH25" ("PLANT_POOP" . "50") ("CREATURE1" . "50"))
    ("MAINT_TECH24" ("CAVE1" . "50") ("LAND3" . "6") ("STELLAR2" . "50"))
    ("MAINT_TECH23" ("LAND3" . "6") ("STELLAR2" . "50"))
    ("MAINT_TECH22" ("YELLOW2" . "100") ("LAND2" . "100"))
    ("MAINT_TECH21" ("FUEL2" . "50") ("LAND3" . "10"))
    ("MAINT_TECH20" ("YELLOW2" . "50"))
    ("MAINT_TECH19" ("LAND3" . "6") ("STELLAR2" . "50"))
    ("MAINT_TECH18" ("LAND3" . "10"))
    ("MAINT_TECH17" ("OXYGEN" . "40") ("LAND2" . "100"))
    ("MAINT_TECH16" ("LAND3" . "6") ("FUEL1" . "50"))
    ("MAINT_TECH15" ("LAND2" . "60"))
    ("MAINT_TECH14" ("LAND2" . "20") ("CAVE2" . "100"))
    ("MAINT_TECH13" ("CAVE1" . "50") ("ROBOT1" . "40"))
    ("MAINT_TECH12" ("LAND2" . "20"))
    ("MAINT_TECH11" ("CATALYST1" . "40"))
    ("MAINT_TECH10" ("ROBOT1" . "20"))
    ("MAINT_TECH9" ("STELLAR2" . "50"))
    ("MAINT_TECH8" ("LAND2" . "50"))
    ("MAINT_TECH7" ("FUEL2" . "20") ("CATALYST1" . "40"))
    ("MAINT_TECH6" ("LAND2" . "100"))
    ("MAINT_TECH5" ("STELLAR2" . "50"))
    ("MAINT_TECH4" ("STELLAR2" . "50") ("CATALYST1" . "40"))
    ("MAINT_TECH3" ("CATALYST2" . "10"))
    ("MAINT_TECH2" ("CAVE1" . "50"))
    ("MAINT_TECH1" ("LAND2" . "30"))
    ("MAINT_FUEL5")
    ("MAINT_FUEL4")
    ("MAINT_FUEL3")
    ("MAINT_FUEL2")
    ("MAINT_FUEL1")
    ("MAINT_FARM5" ("POWERCELL" . "1") ("LAND2" . "100"))
    ("MAINT_FARM4" ("PRODFUEL1" . "1") ("LAND2" . "100"))
    ("MAINT_FARM3" ("POWERCELL" . "1") ("LAND2" . "100"))
    ("MAINT_FARM2" ("PRODFUEL1" . "1") ("LAND2" . "100"))
    ("MAINT_FARM1" ("POWERCELL" . "1") ("LAND2" . "100"))
    ("VEHICLE_GUN" ("YELLOW2" . "100") ("ROBOT1" . "50"))
    ("VEHICLE_LASER1" ("STELLAR2" . "50") ("ROBOT1" . "50"))
    ("VEHICLE_LASER" ("PRODFUEL1" . "2") ("STELLAR2" . "100") ("LAND3" . "25"))
    ("VEHICLE_BOOST" ("NANOTUBES" . "2") ("STELLAR2" . "50") ("LAND3" . "15"))
    ("VEHICLE_SCAN2"
     ("ASTEROID2" . "50")
     ("POWERCELL" . "2")
     ("STELLAR2" . "150"))
    ("VEHICLE_SCAN1"
     ("MICROCHIP" . "2")
     ("POWERCELL" . "2")
     ("STELLAR2" . "100"))
    ("VEHICLE_SCAN" ("MICROCHIP" . "1") ("STELLAR2" . "50"))
    ("VEHICLE_GRIP3" ("TECH_COMP" . "1") ("COLD1" . "50") ("LAND3" . "50"))
    ("VEHICLE_GRIP2" ("TECH_COMP" . "1") ("ROCKETSUB" . "50") ("LAND3" . "50"))
    ("VEHICLE_GRIP1" ("TECH_COMP" . "1") ("LUSH1" . "50") ("LAND3" . "50"))
    ("VEHICLE_ENGINE" ("PRODFUEL1" . "2") ("LAND3" . "25"))
    ("WEAPSLOT_DMG6" ("LUSH1" . "100") ("COLD1" . "100") ("DUSTY1" . "100"))
    ("WEAPSLOT_DMG5" ("RADIO1" . "100") ("TOXIC1" . "100") ("HOT1" . "100"))
    ("WEAPSLOT_DMG4" ("CAVE2" . "100"))
    ("WEAPSLOT_DMG3"
     ("POWERCELL" . "12")
     ("CARBON_SEAL" . "16")
     ("MICROCHIP" . "10"))
    ("WEAPSLOT_DMG2" ("TECH_COMP" . "4"))
    ("WEAPSLOT_DMG1" ("STELLAR2" . "400"))
    ("UT_SMG" ("TECH_COMP" . "1") ("CAVEPROD3" . "1"))
    ("SMG" ("TECH_COMP" . "1") ("LAUNCHSUB2" . "200"))
    ("UT_SHOT" ("TECH_COMP" . "1") ("WATERPROD3" . "1"))
    ("SHOTGUN" ("TECH_COMP" . "1") ("ROBOT1" . "200"))
    ("UT_RAIL" ("TECH_COMP" . "1") ("OXYPROD3" . "1"))
    ("RAILGUN" ("TECH_COMP" . "1") ("FUEL2" . "150") ("STELLAR2" . "200"))
    ("TERRAIN_GREN" ("TECH_COMP" . "1") ("LANDPROD3" . "1"))
    ("GRENADE" ("TECH_COMP" . "1") ("OXYPROD3" . "1"))
    ("LASER_XO" ("LAND2" . "50"))
    ("BOLT_SM" ("LAND2" . "50"))
    ("UT_BOLT" ("TECH_COMP" . "1") ("CAVE_CRAFT" . "1"))
    ("BOLT" ("NANOTUBES" . "3") ("STELLAR2" . "100"))
    ("STRONGLASER"
     ("TECH_COMP" . "2")
     ("CARBON_SEAL" . "1")
     ("NANOTUBES" . "1"))
    ("LASER" ("LAND1" . "60"))
    ("SCOPE" ("TECH_COMP" . "1") ("POWERCELL" . "2"))
    ("GROUND_SHIELD" ("TECH_COMP" . "1") ("POWERCELL" . "2"))
    ("TERRAINEDITOR" ("JELLY" . "1") ("NANOTUBES" . "2"))
    ("UT_SCAN" ("POWERCELL" . "1") ("LAND3" . "100"))
    ("SCAN1" ("LAND1" . "150"))
    ("SCANBINOC1" ("NANOTUBES" . "1"))
    ("SHIPSLOT_DMG6" ("TECH_COMP" . "10") ("STELLAR2" . "600"))
    ("SHIPSLOT_DMG5"
     ("ASTEROID2" . "180")
     ("STELLAR2" . "300")
     ("LAND3" . "200"))
    ("SHIPSLOT_DMG4" ("ROBOT1" . "50") ("LUSH1" . "820"))
    ("SHIPSLOT_DMG3" ("ASTEROID3" . "400"))
    ("SHIPSLOT_DMG2" ("WATER2" . "50") ("LAND3" . "500"))
    ("SHIPSLOT_DMG1" ("STELLAR2" . "700"))
    ("F_HACCESS3" ("BLUE2" . "250") ("CAVEPROD3" . "2") ("AM_HOUSING" . "2"))
    ("F_HACCESS2" ("GREEN2" . "250") ("WATERPROD3" . "2") ("AM_HOUSING" . "2"))
    ("F_HACCESS1" ("RED2" . "250") ("OXYPROD3" . "2") ("AM_HOUSING" . "2"))
    ("F_HDRIVEBOOST3"
     ("AM_HOUSING" . "6")
     ("WATER_CRAFT" . "1")
     ("BLUE2" . "250"))
    ("F_HDRIVEBOOST2"
     ("AM_HOUSING" . "5")
     ("CATA_CRAFT" . "1")
     ("GREEN2" . "250"))
    ("F_HDRIVEBOOST1"
     ("AM_HOUSING" . "4")
     ("OXY_CRAFT" . "1")
     ("RED2" . "250"))
    ("F_HYPERDRIVE"
     ("AM_HOUSING" . "3")
     ("ANTIMATTER" . "3")
     ("STELLAR2" . "500"))
    ("UT_SHIPBLOB" ("TECH_COMP" . "2") ("CAVEPROD3" . "3"))
    ("SHIPPLASMA" ("TECH_COMP" . "2") ("COLD1" . "200"))
    ("UT_SHIPMINI" ("TECH_COMP" . "2") ("CATAPROD3" . "3"))
    ("SHIPMINIGUN" ("TECH_COMP" . "2") ("HOT1" . "200"))
    ("UT_SHIPSHOT" ("TECH_COMP" . "2") ("LANDPROD3" . "3"))
    ("SHIPSHOTGUN" ("TECH_COMP" . "2") ("RADIO1" . "200"))
    ("UT_SHIPLAS" ("TECH_COMP" . "2") ("WATER_CRAFT" . "1"))
    ("SHIPLAS1" ("TECH_COMP" . "1") ("ROCKETSUB" . "100"))
    ("SHIPSCAN_COMBAT" ("TECH_COMP" . "1") ("WALKER_PROD" . "1"))
    ("SHIPSCAN_ECON" ("TECH_COMP" . "1") ("MICROCHIP" . "5"))
    ("UT_SHIPGUN" ("TECH_COMP" . "1") ("CAVE_CRAFT" . "1"))
    ("SHIPGUN1" ("CATALYST2" . "60") ("LAND2" . "100"))
    ("UT_ROCKETS" ("GRENFUEL1" . "4") ("TECH_COMP" . "2"))
    ("SHIPROCKETS" ("FUEL2" . "100") ("YELLOW2" . "200"))
    ("UT_SHIPSHIELD" ("CATALYST2" . "50") ("CAVE_CRAFT" . "1"))
    ("SHIPSHIELD" ("CATALYST2" . "25") ("STELLAR2" . "100"))
    ("HDRIVEBOOST3" ("TECH_COMP" . "3") ("GREEN2" . "250"))
    ("HDRIVEBOOST2" ("TECH_COMP" . "2") ("RED2" . "250"))
    ("HDRIVEBOOST1" ("TECH_COMP" . "1") ("STELLAR2" . "250"))
    ("HYPERDRIVE" ("MICROCHIP" . "5") ("STELLAR2" . "125"))
    ("SHIP_TELEPORT" ("TECH_COMP" . "3") ("ANTIMATTER" . "1"))
    ("UT_LAUNCHER" ("TECH_COMP" . "2") ("ROCKETSUB" . "100") ("JELLY" . "1"))
    ("LAUNCHER" ("JELLY" . "1") ("LAND2" . "100"))
    ("PHOTONIX_CORE" ("FUEL2" . "100") ("LAND2" . "100"))
    ("SHIPJUMP1" ("CASING" . "1") ("CARBON_SEAL" . "1"))
    ("OBSOLETE" ("TECHFRAG" . "100") ("TECH_COMP" . "4"))
    ("STARSUIT" ("ASTEROID2" . "16") ("ROCKETSUB" . "16") ("ASTEROID3" . "16"))
    ("ATLASSUIT" ("ASTEROID3" . "16") ("ATLAS_SEED_10" . "1"))
    ("POWERGLOVE" ("CATALYST2" . "20") ("STELLAR2" . "50"))
    ("UT_JUMP" ("WATER_CRAFT" . "1") ("ROCKETSUB" . "100"))
    ("UT_JET" ("FUEL2" . "100") ("STELLAR2" . "100"))
    ("JET1" ("LAND1" . "100"))
    ("UT_ENERGY" ("OXY_CRAFT" . "1"))
    ("ENERGY" ("LAND1" . "100"))
    ("UT_PROTECT" ("ANTIMATTER" . "1") ("CATA_CRAFT" . "1"))
    ("PROTECT" ("LAND1" . "100"))
    ("U_EXO_ENG4")
    ("U_EXO_ENG3")
    ("U_EXO_ENG2")
    ("U_EXO_ENG1")
    ("U_EXOBOOST4")
    ("U_EXOBOOST3")
    ("U_EXOBOOST2")
    ("U_EXOBOOST1")
    ("U_EXOLAS4")
    ("U_EXOLAS3")
    ("U_EXOLAS2")
    ("U_EXOLAS1")
    ("U_EXOGUN4")
    ("U_EXOGUN3")
    ("U_EXOGUN2")
    ("U_EXOGUN1")
    ("U_SHIPBLOB4")
    ("U_SHIPBLOB3")
    ("U_SHIPBLOB2")
    ("U_SHIPBLOB1")
    ("U_SHIPMINI4")
    ("U_SHIPMINI3")
    ("U_SHIPMINI2")
    ("U_SHIPMINI1")
    ("U_SHIPSHOT4")
    ("U_SHIPSHOT3")
    ("U_SHIPSHOT2")
    ("U_SHIPSHOT1")
    ("U_SHIPLAS4")
    ("U_SHIPLAS3")
    ("U_SHIPLAS2")
    ("U_SHIPLAS1")
    ("U_SHIPGUN4")
    ("U_SHIPGUN3")
    ("U_SHIPGUN2")
    ("U_SHIPGUN1")
    ("U_SHIPSHIELD4")
    ("U_SHIPSHIELD3")
    ("U_SHIPSHIELD2")
    ("U_SHIPSHIELD1")
    ("U_HYPER4")
    ("U_HYPER3")
    ("U_HYPER2")
    ("U_HYPER1")
    ("U_PULSE4")
    ("U_PULSE3")
    ("U_PULSE2")
    ("U_PULSE1")
    ("U_HOTPROT3")
    ("U_HOTPROT2")
    ("U_HOTPROT1")
    ("U_COLDPROT3")
    ("U_COLDPROT2")
    ("U_COLDPROT1")
    ("U_TOX3")
    ("U_TOX2")
    ("U_TOX1")
    ("U_RAD3")
    ("U_RAD2")
    ("U_RAD1")
    ("U_UNW3")
    ("U_UNW2")
    ("U_UNW1")
    ("U_SHIELDBOOST4")
    ("U_SHIELDBOOST3")
    ("U_SHIELDBOOST2")
    ("U_SHIELDBOOST1")
    ("U_JETBOOST4")
    ("U_JETBOOST3")
    ("U_JETBOOST2")
    ("U_JETBOOST1")
    ("U_ENERGY3")
    ("U_ENERGY2")
    ("U_ENERGY1")
    ("U_SMG4")
    ("U_SMG3")
    ("U_SMG2")
    ("U_SMG1")
    ("U_SHOTGUN4")
    ("U_SHOTGUN3")
    ("U_SHOTGUN2")
    ("U_SHOTGUN1")
    ("U_RAIL4")
    ("U_RAIL3")
    ("U_RAIL2")
    ("U_RAIL1")
    ("U_TGRENADE4")
    ("U_TGRENADE3")
    ("U_TGRENADE2")
    ("U_TGRENADE1")
    ("U_GRENADE4")
    ("U_GRENADE3")
    ("U_GRENADE2")
    ("U_GRENADE1")
    ("U_BOLT4")
    ("U_BOLT3")
    ("U_BOLT2")
    ("U_BOLT1")
    ("U_SCANNER4")
    ("U_SCANNER3")
    ("U_SCANNER2")
    ("U_SCANNER1")
    ("U_LASER4")
    ("U_LASER3")
    ("U_LASER2")
    ("U_LASER1")
    ("C_ARCH_H" ("LAND1" . "20"))
    ("C_ARCH" ("LAND1" . "40"))
    ("C_ROOF_C" ("LAND1" . "30"))
    ("C_ROOF_M" ("LAND1" . "25"))
    ("C_ROOF" ("LAND1" . "40"))
    ("C_RAMP_H" ("LAND2" . "5") ("LAND1" . "25"))
    ("C_RAMP" ("LAND2" . "10") ("LAND1" . "50"))
    ("C_FLOOR_Q" ("LAND1" . "20"))
    ("C_GFLOOR" ("LAND1" . "20"))
    ("C_FLOOR" ("LAND1" . "20"))
    ("C_DOORWINDOW" ("LAND2" . "10") ("LAND1" . "40"))
    ("C_DOOR_H" ("LAND1" . "20"))
    ("C_SDOOR" ("LAND1" . "20"))
    ("C_DOOR" ("LAND1" . "40"))
    ("C_WALL_WINDOW" ("FARMPROD3" . "1") ("LAND1" . "40"))
    ("C_WALLDIAGONAL" ("LAND1" . "20"))
    ("C_WALL_Q_H" ("LAND1" . "20"))
    ("C_WALL_Q" ("LAND1" . "20"))
    ("C_WALL_H" ("LAND1" . "20"))
    ("C_WALL" ("LAND1" . "40"))
    ("M_ARCH_H" ("LAND1" . "20"))
    ("M_ARCH" ("LAND1" . "40"))
    ("M_ROOF_C" ("LAND1" . "10") ("FUEL1" . "20"))
    ("M_ROOF_M" ("LAND1" . "10") ("FUEL1" . "20"))
    ("M_ROOF" ("LAND1" . "10") ("LAND1" . "20"))
    ("M_RAMP_H" ("LAND2" . "5") ("LAND1" . "25"))
    ("M_RAMP" ("LAND2" . "10") ("LAND1" . "50"))
    ("M_FLOOR_Q" ("LAND1" . "20"))
    ("M_GFLOOR" ("LAND1" . "20"))
    ("M_FLOOR" ("LAND1" . "20"))
    ("M_DOORWINDOW" ("LAND2" . "10") ("LAND1" . "40"))
    ("M_DOOR_H" ("FUEL1" . "20"))
    ("M_DOOR" ("LAND1" . "40"))
    ("M_SDOOR" ("LAND1" . "20"))
    ("M_WALL_WINDOW" ("FARMPROD3" . "1") ("LAND1" . "40"))
    ("M_WALLDIAGONAL" ("LAND1" . "20"))
    ("M_WALL_Q_H" ("FUEL1" . "20"))
    ("M_WALL_Q" ("LAND1" . "20"))
    ("M_WALL_H" ("FUEL1" . "20"))
    ("M_WALL" ("LAND1" . "40"))
    ("W_ARCH_H" ("FUEL1" . "20"))
    ("W_ARCH" ("FUEL1" . "40"))
    ("W_ROOF_C" ("LAND1" . "10") ("FUEL1" . "20"))
    ("W_ROOF_M" ("LAND1" . "10") ("FUEL1" . "20"))
    ("W_ROOF" ("LAND1" . "10") ("FUEL1" . "20"))
    ("W_RAMP_H" ("LAND2" . "5") ("FUEL1" . "25"))
    ("W_RAMP" ("LAND2" . "10") ("FUEL1" . "50"))
    ("W_FLOOR_Q" ("FUEL1" . "20"))
    ("W_GFLOOR" ("FUEL1" . "20"))
    ("W_FLOOR" ("FUEL1" . "20"))
    ("W_DOORWINDOW" ("LAND2" . "10") ("FUEL1" . "40"))
    ("W_DOOR_H" ("FUEL1" . "20"))
    ("W_DOOR" ("FUEL1" . "40"))
    ("W_SDOOR" ("FUEL1" . "20"))
    ("W_WALL_WINDOW" ("FARMPROD3" . "1") ("FUEL1" . "40"))
    ("W_WALLDIAGONAL" ("FUEL1" . "20"))
    ("W_WALL_Q_H" ("FUEL1" . "20"))
    ("W_WALL_Q" ("FUEL1" . "20"))
    ("W_WALL_H" ("FUEL1" . "20"))
    ("W_WALL" ("FUEL1" . "40"))
    ("CARBONPLANTER" ("FUEL1" . "20"))
    ("CREATHOLOGRAM" ("LAND2" . "100"))
    ("NPCEXPLORER001" ("LAND2" . "50"))
    ("HEALTHPLANT" ("FUEL1" . "10"))
    ("CORRIDOR_WINDOW" ("FARMPROD3" . "1") ("CAVE2" . "5"))
    ("BUILDDECALSIMP4" ("FUEL1" . "20"))
    ("BUILDDECALSIMP3" ("FUEL1" . "20"))
    ("BUILDDECALSIMP2" ("FUEL1" . "20"))
    ("BUILDDECALSIMP1" ("FUEL1" . "20"))
    ("BUILDDECALVIS5" ("FUEL1" . "20"))
    ("BUILDDECALVIS4" ("FUEL1" . "20"))
    ("BUILDDECALVIS3" ("FUEL1" . "20"))
    ("BUILDDECALVIS2" ("FUEL1" . "20"))
    ("BUILDDECALVIS1" ("FUEL1" . "20"))
    ("BUILDDECALNUM9" ("FUEL1" . "20"))
    ("BUILDDECALNUM8" ("FUEL1" . "20"))
    ("BUILDDECALNUM7" ("FUEL1" . "20"))
    ("BUILDDECALNUM6" ("FUEL1" . "20"))
    ("BUILDDECALNUM5" ("FUEL1" . "20"))
    ("BUILDDECALNUM4" ("FUEL1" . "20"))
    ("BUILDDECALNUM3" ("FUEL1" . "20"))
    ("BUILDDECALNUM2" ("FUEL1" . "20"))
    ("BUILDDECALNUM1" ("FUEL1" . "20"))
    ("BUILDDECALNUM0" ("FUEL1" . "20"))
    ("BUILDDECALNMS" ("FUEL1" . "20"))
    ("BUILDDECALHELLO" ("FUEL1" . "20"))
    ("BUILDDECAL2" ("FUEL1" . "20"))
    ("BUILDDECAL" ("FUEL1" . "20"))
    ("RACE_RAMP" ("CASING" . "5"))
    ("RACE_BOOSTER" ("JELLY" . "2") ("CASING" . "5"))
    ("RACE_START_SHIP"
     ("POWERCELL" . "1")
     ("MICROCHIP" . "2")
     ("CASING" . "5"))
    ("RACE_START" ("POWERCELL" . "1") ("MICROCHIP" . "2") ("CASING" . "5"))
    ("S_CONTAINER9" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER8" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER7" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER6" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER5" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER4" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER3" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER2" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER1" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("S_CONTAINER0" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CORRIDORX_SPACE" ("ROCKETSUB" . "10") ("ASTEROID1" . "80"))
    ("CUBEWALL_SPACE" ("ASTEROID1" . "50"))
    ("CORSTAIRS_SPACE" ("ASTEROID1" . "50"))
    ("CORRIDORT_SPACE" ("ROCKETSUB" . "10") ("ASTEROID1" . "80"))
    ("CORRIDORL_SPACE" ("ROCKETSUB" . "10") ("ASTEROID1" . "80"))
    ("CORRIDOR_SPACE" ("ROCKETSUB" . "10") ("ASTEROID1" . "80"))
    ("BRIDGECONNECTOR" ("ROCKETSUB" . "20") ("ASTEROID1" . "120"))
    ("CUBEROOMC_SPACE" ("ROCKETSUB" . "20") ("ASTEROID1" . "120"))
    ("CUBEROOMB_SPACE" ("ROCKETSUB" . "20") ("ASTEROID1" . "120"))
    ("CUBEROOM_SPACE" ("ROCKETSUB" . "20") ("ASTEROID1" . "120"))
    ("DRESSING_TABLE" ("LAND1" . "10"))
    ("O2_HARVESTER" ("JELLY" . "3") ("PRODFUEL1" . "5") ("CASING" . "5"))
    ("BUILD_REFINER3"
     ("MICROCHIP" . "5")
     ("CATALYST2" . "100")
     ("STELLAR2" . "200"))
    ("BUILD_REFINER2" ("JELLY" . "5") ("LAND3" . "100"))
    ("BUILD_REFINER1" ("OXYGEN" . "30") ("CASING" . "1"))
    ("BP_ANALYSER" ("NANOTUBES" . "1") ("LAND3" . "20"))
    ("NPCFRIGTERM"
     ("ROCKETSUB" . "10")
     ("ASTEROID2" . "40")
     ("ASTEROID1" . "120"))
    ("BASECAPSULE" ("LAND2" . "50"))
    ("TELEPORTER" ("POWERCELL" . "1") ("CAVE2" . "50"))
    ("BASE_FLAG" ("STELLAR2" . "40"))
    ("WALLCURVED" ("LAND1" . "20"))
    ("CUBESOLID" ("LAND1" . "20"))
    ("PIPESHAPE" ("LAND1" . "20"))
    ("CURVEPIPESHAPE" ("LAND1" . "20"))
    ("PYRAMIDSHAPE" ("LAND1" . "20"))
    ("WEDGESMALLSHAPE" ("LAND1" . "20"))
    ("WEDGESHAPE" ("LAND1" . "20"))
    ("WALLTALL" ("LAND1" . "40"))
    ("WALLFLOORLADDER" ("LAND1" . "20"))
    ("CRATELCYLINDER" ("ANTIMATTER" . "1") ("CAVE2" . "10"))
    ("CRATELRARE" ("ANTIMATTER" . "1") ("CAVE2" . "10"))
    ("BUILDWORKTOP" ("LAND2" . "10"))
    ("WALLSCREENB2" ("LAND2" . "10"))
    ("WALLSCREENB" ("LAND2" . "10"))
    ("BOXEDSCREEN" ("LAND2" . "10"))
    ("BUILDAMCRATE" ("LAND2" . "10"))
    ("BUILDLCRATE" ("LAND2" . "10"))
    ("OCTACABINET" ("LAND2" . "10"))
    ("ROBOTICARM" ("LAND2" . "10"))
    ("BUILDFLATPANEL" ("CATALYST1" . "10") ("LAND1" . "10"))
    ("BUILDLABLAMP" ("CATALYST1" . "10"))
    ("BUILDCANRACK" ("FUEL2" . "10"))
    ("BUILDSIDEPANEL" ("CATALYST1" . "10") ("LAND1" . "10"))
    ("BUILDHCABINET" ("FUEL2" . "10"))
    ("BUILDLIGHTTABLE" ("LAND1" . "10") ("CATALYST1" . "10"))
    ("BUILDLOCKER" ("LAND2" . "10"))
    ("SHELFPANEL" ("LAND2" . "10"))
    ("STORAGEPANEL" ("LAND2" . "10"))
    ("BUILDSOFA2" ("FUEL2" . "10"))
    ("BUILDSOFA2L" ("FUEL2" . "10"))
    ("BUILDSOFA" ("FUEL2" . "10"))
    ("CURVEDDESK" ("FUEL2" . "10") ("LAND2" . "5"))
    ("WEAPONRACK" ("CAVE1" . "5") ("LAND2" . "5"))
    ("BUILDSIMPLEDESK" ("FUEL2" . "10"))
    ("PLANTPOT3" ("FUEL1" . "15"))
    ("PLANTPOT2" ("FUEL1" . "15"))
    ("PLANTPOT1" ("FUEL1" . "15"))
    ("LARGEDESK" ("FUEL2" . "5") ("LAND2" . "5"))
    ("WALLDOOR" ("LAND2" . "30"))
    ("MONITORDESK" ("CAVE1" . "5") ("LAND2" . "5"))
    ("CEILINGLIGHT" ("CAVE1" . "5") ("LAND2" . "5"))
    ("ROOFMONITOR" ("CAVE1" . "5") ("LAND2" . "5"))
    ("FLOORMAT1" ("FUEL1" . "5") ("LAND2" . "5"))
    ("SERVERSTACK" ("CAVE1" . "5") ("LAND2" . "10"))
    ("DRAWS" ("LAND2" . "10"))
    ("WALLFLAG3" ("FUEL1" . "5") ("LAND2" . "5"))
    ("WALLFLAG2" ("FUEL1" . "5") ("LAND2" . "5"))
    ("WALLFLAG1" ("FUEL1" . "5") ("LAND2" . "5"))
    ("FLAG4" ("FUEL1" . "5") ("LAND2" . "5"))
    ("FLAG3" ("FUEL1" . "5") ("LAND2" . "5"))
    ("FLAG2" ("FUEL1" . "5") ("LAND2" . "5"))
    ("FLAG1" ("FUEL1" . "5") ("LAND2" . "5"))
    ("CUBEWINDOWSMALL" ("FARMPROD3" . "1") ("CAVE2" . "5"))
    ("CUBEWINDOWOVAL" ("FARMPROD3" . "1") ("CAVE2" . "5"))
    ("SPHERESHAPE" ("LAND1" . "20"))
    ("CUBESHAPE" ("LAND1" . "20"))
    ("CYLINDERSHAPE" ("LAND1" . "20"))
    ("ROOMFLOOR" ("LAND1" . "20"))
    ("CORNERPOST" ("LAND1" . "10"))
    ("WALL" ("LAND1" . "20"))
    ("CHEST" ("POWERCELL" . "1") ("LAND2" . "5"))
    ("BLDWALLUNIT" ("CAVE1" . "5") ("LAND2" . "10"))
    ("PLANTPOT" ("FUEL1" . "10"))
    ("WALLSCREEN" ("CAVE1" . "5") ("FUEL2" . "5"))
    ("WALLFAN" ("CAVE1" . "5") ("FUEL2" . "5"))
    ("TECHPANEL" ("CAVE1" . "5") ("FUEL2" . "5"))
    ("CUBELADDER" ("LAND2" . "10"))
    ("CUBEWINDOW" ("FARMPROD3" . "1") ("CAVE2" . "10"))
    ("BUILDPAVINGTALL" ("LAND2" . "25"))
    ("BUILDBED" ("FUEL2" . "10"))
    ("BUILDTABLE3" ("FUEL2" . "10"))
    ("BUILDTABLE2" ("FUEL2" . "10"))
    ("BUILDTABLE" ("FUEL2" . "10"))
    ("BUILDCHAIR3" ("TRA_COMMODITY2" . "1") ("LAND2" . "5"))
    ("BUILDCHAIR2" ("TRA_COMMODITY2" . "1") ("LAND2" . "5"))
    ("BUILDCHAIR" ("TRA_COMMODITY2" . "1") ("FUEL2" . "5"))
    ("BUILDWINDOW" ("FARMPROD3" . "1") ("CAVE2" . "5"))
    ("BUILDLADDER" ("LAND2" . "30"))
    ("BUILDPAVING_BIG" ("LAND2" . "5"))
    ("BUILDPAVING" ("LAND2" . "5"))
    ("BUILDLIGHT3" ("CATALYST1" . "5"))
    ("BUILDLIGHT2" ("CATALYST1" . "5"))
    ("BUILDLIGHT" ("CATALYST1" . "5"))
    ("SMALLLIGHT" ("CATALYST1" . "5"))
    ("WALLLIGHTWHITE" ("CATALYST1" . "5"))
    ("WALLLIGHTRED" ("CATALYST1" . "5"))
    ("WALLLIGHTGREEN" ("CATALYST1" . "5"))
    ("WALLLIGHTYELLOW" ("CATALYST1" . "5"))
    ("WALLLIGHTPINK" ("CATALYST1" . "5"))
    ("WALLLIGHTBLUE" ("CATALYST1" . "5"))
    ("CONTAINER9" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER8" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER7" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER6" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER5" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER4" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER3" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER2" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER1" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("CONTAINER0" ("CATALYST1" . "20") ("LAND3" . "50"))
    ("NIPPLANT" ("TRA_CURIO2" . "1"))
    ("PEARLPLANT" ("LUSH1" . "20") ("BLUE2" . "60"))
    ("SACVENOMPLANT" ("CAVE2" . "100") ("GREEN2" . "100"))
    ("GRAVPLANT" ("LAND3" . "25") ("CAVE2" . "120") ("STELLAR2" . "25"))
    ("POOPPLANT" ("PLANT_POOP" . "40"))
    ("CREATUREPLANT" ("CREATURE1" . "40"))
    ("SCORCHEDPLANT" ("HOT1" . "25") ("PLANT_HOT" . "50"))
    ("LUSHPLANT" ("LUSH1" . "25") ("PLANT_LUSH" . "50"))
    ("BARRENPLANT" ("DUSTY1" . "25") ("PLANT_DUST" . "50"))
    ("RADIOPLANT" ("RADIO1" . "25") ("PLANT_RADIO" . "50"))
    ("SNOWPLANT" ("COLD1" . "25") ("PLANT_SNOW" . "50"))
    ("TOXICPLANT" ("TOXIC1" . "25") ("PLANT_TOXIC" . "50"))
    ("PLANTERMEGA" ("FUEL1" . "50") ("CAVE2" . "50") ("LAND2" . "60"))
    ("PLANTER" ("FUEL1" . "20") ("CAVE2" . "20") ("LAND2" . "30"))
    ("NPCBUILDERTERM" ("LAND2" . "25") ("STELLAR2" . "40"))
    ("NPCVEHICLETERM" ("LAUNCHSUB" . "25") ("STELLAR2" . "40"))
    ("NPCFARMTERM" ("FUEL2" . "25") ("STELLAR2" . "40"))
    ("NPCWEAPONTERM" ("ROBOT1" . "25") ("STELLAR2" . "40"))
    ("NPCSCIENCETERM" ("LAND3" . "25") ("STELLAR2" . "40"))
    ("MESSAGE" ("LAND2" . "20"))
    ("SHIPSUMMON" ("LAND2" . "10"))
    ("BUILDSAVE" ("JELLY" . "1") ("CASING" . "2"))
    ("BUILDGASHARVEST"
     ("CARBON_SEAL" . "2")
     ("CASING" . "2")
     ("TOXIC1" . "100"))
    ("BUILDHARVESTER" ("POWERCELL2" . "1") ("CASING" . "2") ("RADIO1" . "100"))
    ("BUILDSIGNAL" ("CATALYST1" . "15") ("NANOTUBES" . "1") ("CASING" . "1"))
    ("BUILDBEACON" ("MICROCHIP" . "1") ("POWERCELL" . "2") ("CASING" . "1"))
    ("MESSAGEMODULE" ("NANOTUBES" . "1") ("CASING" . "1"))
    ("SHIELDSTATION" ("HOT1" . "50") ("CAVE2" . "20") ("CASING" . "1"))
    ("HEALTHSTATION" ("RADIO1" . "50") ("CAVE2" . "20") ("CASING" . "1"))
    ("SUMMON_GARAGE"
     ("ANTIMATTER" . "1")
     ("POWERCELL" . "4")
     ("LAND3" . "100"))
    ("GARAGE_B" ("LUSH1" . "100") ("POWERCELL" . "4") ("CASING" . "5"))
    ("GARAGE_L" ("LUSH1" . "100") ("POWERCELL" . "4") ("CASING" . "5"))
    ("GARAGE_M" ("LUSH1" . "100") ("POWERCELL" . "4") ("CASING" . "5"))
    ("GARAGE_S" ("LUSH1" . "100") ("POWERCELL" . "4") ("CASING" . "5"))
    ("BUILDTERMINAL" ("MICROCHIP" . "3") ("LAND3" . "25"))
    ("BUILDLANDINGPAD"
     ("MICROCHIP" . "2")
     ("POWERCELL" . "2")
     ("CASING" . "10"))
    ("MAINROOMCUBEF" ("LAND2" . "200"))
    ("MAINROOMCUBE" ("LAND2" . "350"))
    ("CORRIDORC" ("LAND2" . "100"))
    ("MAINROOMFRAME" ("LAND2" . "200"))
    ("VIEWSPHERE" ("FARMPROD3" . "3") ("LAND3" . "10"))
    ("DOOR2" ("LAND2" . "40") ("CAVE2" . "40"))
    ("BUILDDOOR" ("LAND2" . "50"))
    ("CUBESTAIRS" ("FUEL1" . "30") ("LAND2" . "50"))
    ("CUBEROOF" ("LAND2" . "80"))
    ("CUBEWALL" ("LAND2" . "80"))
    ("CUBEINNERDOOR" ("LAND2" . "50"))
    ("CUBEFRAME" ("LAND2" . "80"))
    ("CUBEGLASS" ("FARMPROD3" . "2") ("CAVE2" . "20"))
    ("CUBEROOMCURVED" ("LAND2" . "100"))
    ("CURVEDCUBEROOF" ("FARMPROD3" . "1") ("LAND2" . "100"))
    ("BIOROOM" ("FARMPROD3" . "5") ("LAND3" . "25"))
    ("BUILDRAMP" ("FUEL1" . "50") ("LAND2" . "50"))
    ("GLASSCORRIDOR" ("FARMPROD3" . "1") ("LAND2" . "100"))
    ("CUBEFLOOR" ("LAND2" . "80"))
    ("CUBEFOUND4" ("LAND2" . "80"))
    ("CUBEFOUND" ("LAND2" . "80"))
    ("CUBEROOM" ("LAND2" . "200"))
    ("BUILDTOWER" ("LAND2" . "50"))
    ("FOUNDLEG" ("LAND2" . "50"))
    ("FOUNDLEG4" ("LAND2" . "50"))
    ("MAINROOM" ("LAND2" . "350"))
    ("CORRIDORX" ("LAND2" . "100"))
    ("CORRIDORT" ("LAND2" . "100"))
    ("CORRIDORL" ("LAND2" . "100"))
    ("CORRIDOR" ("LAND2" . "100"))
    ("FOUNDATION" ("LAND2" . "150"))
    ("BASE_MEDPLANT03" ("FUEL1" . "40"))
    ("BASE_MEDPLANT02" ("FUEL1" . "40"))
    ("BASE_MEDPLANT01" ("FUEL1" . "40"))
    ("BASE_TREE03" ("FUEL1" . "80"))
    ("BASE_TREE02" ("FUEL1" . "80"))
    ("BASE_TREE01" ("FUEL1" . "80"))
    ("BASE_TOYSPHERE" ("ASTEROID3" . "30") ("LAND2" . "30"))
    ("BASE_TOYCUBE" ("ASTEROID3" . "30") ("LAND2" . "30"))
    ("BASE_ROBOTOY" ("ASTEROID3" . "30") ("ROBOT1" . "30"))
    ("SPEC_VYK_BOOTS")
    ("SPEC_VYK_LEGS")
    ("SPEC_VYK_GLOVES")
    ("SPEC_VYK_TORSO")
    ("SPEC_VYK_ARMOUR")
    ("SPEC_HELMET02")
    ("SPEC_HELMET01")
    ("SPEC_DECAL08" ("FUEL1" . "20"))
    ("SPEC_DECAL07" ("FUEL1" . "20"))
    ("SPEC_DECAL06" ("FUEL1" . "20"))
    ("SPEC_DECAL05" ("FUEL1" . "20"))
    ("SPEC_DECAL04" ("FUEL1" . "20"))
    ("SPEC_DECAL03" ("FUEL1" . "20"))
    ("SPEC_DECAL02" ("FUEL1" . "20"))
    ("SPEC_DECAL01" ("FUEL1" . "20"))
    ("SPEC_EMOTE04")
    ("SPEC_EMOTE03")
    ("SPEC_EMOTE02")
    ("SPEC_EMOTE01")
    ("STATUE_ASTRO_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_ASTRO_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_ASTRO_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_ATLAS_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_ATLAS_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_ATLAS_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_WALK_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_WALK_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_WALK_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_SHIP_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_SHIP_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_SHIP_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_GEK_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_GEK_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_GEK_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_DIP_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_DIP_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_DIP_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("STATUE_BLOB_G" ("ASTEROID2" . "30") ("LAND2" . "30"))
    ("STATUE_BLOB_S" ("ASTEROID1" . "20") ("LAND2" . "20"))
    ("STATUE_BLOB_B" ("YELLOW2" . "15") ("LAND2" . "15"))
    ("SPEC_XOHELMET")
    ("FIENDCORE")
    ("HEXCORE")
    ("ATLAS_SEED_10" ("ASTEROID2" . "100") ("ATLAS_SEED_9" . "1"))
    ("ATLAS_SEED_9" ("BLUE2" . "100") ("ATLAS_SEED_8" . "1"))
    ("ATLAS_SEED_8" ("GREEN2" . "100") ("ATLAS_SEED_7" . "1"))
    ("ATLAS_SEED_7" ("RED2" . "100") ("ATLAS_SEED_6" . "1"))
    ("ATLAS_SEED_6" ("YELLOW2" . "100") ("ATLAS_SEED_5" . "1"))
    ("ATLAS_SEED_5" ("STELLAR2" . "25") ("ATLAS_SEED_4" . "1"))
    ("ATLAS_SEED_4" ("LAND3" . "5") ("ATLAS_SEED_3" . "1"))
    ("ATLAS_SEED_3" ("CAVE2" . "100") ("ATLAS_SEED_2" . "1"))
    ("ATLAS_SEED_2" ("LAND2" . "100") ("ATLAS_SEED_1" . "1"))
    ("ATLAS_SEED_1" ("STELLAR2" . "100"))
    ("ATLAS_STONE")
    ("TRA_TECH5")
    ("TRA_TECH4")
    ("TRA_TECH3")
    ("TRA_TECH2")
    ("TRA_TECH1")
    ("TRA_MINERALS5")
    ("TRA_MINERALS4")
    ("TRA_MINERALS3")
    ("TRA_MINERALS2")
    ("TRA_MINERALS1")
    ("TRA_EXOTICS5")
    ("TRA_EXOTICS4")
    ("TRA_EXOTICS3")
    ("TRA_EXOTICS2")
    ("TRA_EXOTICS1")
    ("TRA_ENERGY5")
    ("TRA_ENERGY4")
    ("TRA_ENERGY3")
    ("TRA_ENERGY2")
    ("TRA_ENERGY1")
    ("TRA_COMPONENT5")
    ("TRA_COMPONENT4")
    ("TRA_COMPONENT3")
    ("TRA_COMPONENT2")
    ("TRA_COMPONENT1")
    ("TRA_COMMODITY5")
    ("TRA_COMMODITY4")
    ("TRA_COMMODITY3")
    ("TRA_COMMODITY2")
    ("TRA_COMMODITY1")
    ("TRA_ALLOY5")
    ("TRA_ALLOY4")
    ("TRA_ALLOY3")
    ("TRA_ALLOY2")
    ("TRA_ALLOY1")
    ("ULTRAPROD2" ("ALLOY8" . "1") ("MEGAPROD3" . "1") ("MEGAPROD2" . "1"))
    ("ULTRAPROD1" ("ALLOY7" . "1") ("MEGAPROD2" . "1") ("MEGAPROD1" . "1"))
    ("MEGAPROD3" ("COMPOUND6" . "1") ("FARMPROD8" . "1"))
    ("MEGAPROD2" ("COMPOUND5" . "1") ("FARMPROD9" . "1"))
    ("MEGAPROD1" ("COMPOUND4" . "1") ("FARMPROD7" . "1"))
    ("COMPOUND6" ("REACTION1" . "1") ("COMPOUND3" . "1"))
    ("COMPOUND5" ("REACTION2" . "1") ("COMPOUND2" . "1"))
    ("COMPOUND4" ("REACTION3" . "1") ("COMPOUND1" . "1"))
    ("COMPOUND3" ("REACTION3" . "1") ("REACTION2" . "1"))
    ("COMPOUND2" ("REACTION3" . "1") ("REACTION1" . "1"))
    ("COMPOUND1" ("REACTION2" . "1") ("REACTION1" . "1"))
    ("REACTION3" ("FUEL2" . "50") ("GAS3" . "250"))
    ("REACTION2" ("FUEL2" . "50") ("GAS2" . "250"))
    ("REACTION1" ("FUEL2" . "50") ("GAS1" . "250"))
    ("FARMPROD9" ("FARMPROD5" . "1") ("FARMPROD4" . "1"))
    ("FARMPROD8" ("FARMPROD3" . "5") ("FARMPROD2" . "1"))
    ("FARMPROD7" ("FARMPROD6" . "1") ("FARMPROD1" . "1"))
    ("FARMPROD6" ("PLANT_DUST" . "200"))
    ("FARMPROD5" ("PLANT_LUSH" . "200") ("PLANT_DUST" . "100"))
    ("FARMPROD4" ("PLANT_HOT" . "200") ("PLANT_SNOW" . "100"))
    ("FARMPROD3" ("PLANT_SNOW" . "50"))
    ("FARMPROD2" ("PLANT_RADIO" . "400") ("PLANT_POOP" . "50"))
    ("FARMPROD1" ("PLANT_TOXIC" . "600") ("CREATURE1" . "25"))
    ("EXP_CURIO2")
    ("EXP_CURIO1")
    ("WAR_CURIO2")
    ("WAR_CURIO1")
    ("NIPNIPBUDS")
    ("TRA_CURIO2")
    ("TRA_CURIO1")
    ("FRIG_BOOST_SPD" ("ASTEROID2" . "50") ("QUAD_PROD" . "2"))
    ("FRIG_BOOST_COM" ("ASTEROID2" . "50") ("WALKER_PROD" . "1"))
    ("FRIG_BOOST_MIN" ("ASTEROID2" . "50") ("CAVE_CRAFT" . "1"))
    ("FRIG_BOOST_EXP" ("ASTEROID2" . "50") ("OXY_CRAFT" . "1"))
    ("FRIG_BOOST_TRA" ("ASTEROID2" . "50") ("CATA_CRAFT" . "1"))
    ("FRIGATE_FUEL_3" ("ROCKETSUB" . "200") ("LAUNCHSUB" . "200"))
    ("FRIGATE_FUEL_2" ("ROCKETSUB" . "100") ("LAUNCHSUB" . "100"))
    ("FRIGATE_FUEL_1" ("ROCKETSUB" . "50") ("LAUNCHSUB" . "50"))
    ("BP_SALVAGE")
    ("MIND_ARC" ("MICROCHIP" . "1") ("FARMPROD8" . "1") ("STELLAR2" . "25"))
    ("POLICE_TOKEN")
    ("ACCESS3" ("MICROCHIP" . "1") ("GREEN2" . "200"))
    ("ACCESS2" ("MICROCHIP" . "1") ("RED2" . "200"))
    ("ACCESS1" ("MICROCHIP" . "1") ("YELLOW2" . "200"))
    ("NAV_DATA_DROP")
    ("NAV_DATA")
    ("ARTIFACT_KEY")
    ("ALLOY8" ("ALLOY6" . "1") ("ALLOY5" . "1") ("ALLOY1" . "1"))
    ("ALLOY7" ("ALLOY4" . "1") ("ALLOY3" . "1") ("ALLOY2" . "1"))
    ("ALLOY6" ("CAVE2" . "50") ("COLD1" . "50"))
    ("ALLOY5" ("CAVE2" . "50") ("HOT1" . "50"))
    ("ALLOY4" ("LAND2" . "100") ("RADIO1" . "50"))
    ("ALLOY3" ("CAVE2" . "50") ("TOXIC1" . "50"))
    ("ALLOY2" ("LAND2" . "100") ("DUSTY1" . "50"))
    ("ALLOY1" ("CAVE2" . "50") ("LUSH1" . "50"))
    ("CAVECUBE")
    ("ALBUMENPEARL")
    ("GRAVBALL")
    ("SACVENOM")
    ("OXYPROD3" ("OXYGEN" . "150"))
    ("CATAPROD3" ("CATALYST2" . "150"))
    ("WATERPROD3" ("WATER2" . "150"))
    ("CAVEPROD3" ("CAVE2" . "150"))
    ("LANDPROD3" ("LAND2" . "150"))
    ("FUELPROD3" ("FUEL2" . "150"))
    ("TECH_COMP")
    ("WALKER_PROD")
    ("QUAD_PROD")
    ("CATA_CRAFT" ("LAND1" . "40") ("CATALYST2" . "40"))
    ("CAVE_CRAFT" ("CAVE2" . "50"))
    ("WATER_CRAFT" ("WATER2" . "50"))
    ("OXY_CRAFT" ("LAND2" . "30") ("OXYGEN" . "90"))
    ("HYPERFUEL1" ("ANTIMATTER" . "1") ("AM_HOUSING" . "1"))
    ("ANTIMATTER" ("FUEL2" . "20") ("STELLAR2" . "25"))
    ("AM_HOUSING" ("LAND1" . "50") ("OXYGEN" . "30"))
    ("AMMO" ("LAND1" . "6"))
    ("GRENFUEL1" ("CASING" . "1") ("OXYGEN" . "50"))
    ("LAUNCHFUEL" ("CASING" . "1") ("LAUNCHSUB" . "40"))
    ("JELLY" ("LAUNCHSUB" . "40"))
    ("POWERCELL2" ("LAND2" . "20") ("CAVE2" . "25"))
    ("POWERCELL" ("LAND1" . "20") ("CAVE1" . "25"))
    ("PRODFUEL2" ("FUEL1" . "20") ("JELLY" . "1"))
    ("PRODFUEL1" ("LAND1" . "20") ("OXYGEN" . "25"))
    ("MICROCHIP" ("NANOTUBES" . "1") ("STELLAR2" . "40"))
    ("CARBON_SEAL" ("FUEL2" . "30"))
    ("NANOTUBES" ("FUEL1" . "50"))
    ("CASING" ("LAND1" . "50"))))
(for ((r generated-recipes)) (add-recipe-by-names r))
